#!/usr/bin/env python3
"""
Generate simdbitpacking_u16.c — SIMD bit-packing/unpacking for uint16,
with fused sum aggregation (no output writes during unpack).

Supports 128-bit (AVX) and 256-bit (AVX2) register widths.

Usage:
  python gen_simdbitpacking_u16.py --width 128   # AVX (128-bit registers)
  python gen_simdbitpacking_u16.py --width 256   # AVX2 (256-bit registers)
"""
import argparse
import os
import sys

LANE_BITS = 16
MAX_BIT = 16


def intrinsics(width):
    """Return a dict of intrinsic names for the given register width."""
    if width == 128:
        return dict(
            reg='__m128i',
            load='_mm_loadu_si128',
            store='_mm_storeu_si128',
            setzero='_mm_setzero_si128',
            or_fn='_mm_or_si128',
            and_fn='_mm_and_si128',
            slli='_mm_slli_epi16',
            srli='_mm_srli_epi16',
            set1='_mm_set1_epi16',
            add='_mm_add_epi32',
            unpacklo='_mm_unpacklo_epi16',
            unpackhi='_mm_unpackhi_epi16',
            srli_bytes='_mm_srli_si128',
            extract16='_mm_extract_epi16',
        )
    else:
        return dict(
            reg='__m256i',
            load='_mm256_loadu_si256',
            store='_mm256_storeu_si256',
            setzero='_mm256_setzero_si256',
            or_fn='_mm256_or_si256',
            and_fn='_mm256_and_si256',
            slli='_mm256_slli_epi16',
            srli='_mm256_srli_epi16',
            set1='_mm256_set1_epi16',
            add='_mm256_add_epi32',
            unpacklo='_mm256_unpacklo_epi16',
            unpackhi='_mm256_unpackhi_epi16',
        )


def gen_header(I):
    width = I['width']
    lines = []
    lines.append(f"""\
/**
 * Auto-generated uint16 SIMD bit-packing with fused sum aggregation.
 * Generated by gen_simdbitpacking_u16.py (width={width})
 *
 * This code is released under a BSD License.
 */
#include "simdbitpacking_u16.h"
#include <string.h>
""")

    block = I['block']
    lanes = I['lanes']

    lines.append(f"#define SIMDBlockSize_u16 {block}")
    lines.append("")

    if width == 128:
        lines.append(f"static const {I['reg']} kZero = {{0, 0}};")
    else:
        lines.append(f"static const {I['reg']} kZero = {{0, 0, 0, 0}};")
    lines.append("")

    lines.append(f"static void aggregate_sums_u16({I['reg']} OutReg, {I['reg']}* sum) {{")
    lines.append(f"    /* Zero-extend 8 x uint16 -> 4 x int32, then accumulate.")
    lines.append(f"       _mm_madd_epi16 treats inputs as signed — wrong for values > 32767.")
    lines.append(f"       3 instructions / 8 values = 0.375 inst/val. */")
    lines.append(f"    *sum = {I['add']}(*sum, {I['unpacklo']}(OutReg, kZero));")
    lines.append(f"    *sum = {I['add']}(*sum, {I['unpackhi']}(OutReg, kZero));")
    lines.append("}")
    lines.append("")

    # AVX2-only delta+zigzag helpers, used by simdunpack_u16_delta_{local,carry}.
    if width == 256:
        lines.append("""\
/* ── Delta+ZigZag helpers (AVX2, 16 uint16 lanes) ─────────────────────────── */

static __inline__ uint16_t ZigzagDec16_simdcomp(uint16_t z) {
    return (uint16_t)((z >> 1) ^ (uint16_t)(-(int)(z & 1)));
}

static __inline__ __m256i zigzag_dec_u16_avx2(__m256i x) {
    __m256i odd = _mm256_and_si256(x, _mm256_set1_epi16(1));
    __m256i neg_odd = _mm256_sub_epi16(_mm256_setzero_si256(), odd);
    __m256i half = _mm256_srli_epi16(x, 1);
    return _mm256_xor_si256(half, neg_odd);
}

static __inline__ __m256i prefix_sum_u16_avx2(__m256i x) {
    /* 8-lane Sklansky prefix sum within each 128-bit half (3 levels). */
    x = _mm256_add_epi16(x, _mm256_slli_si256(x, 2));
    x = _mm256_add_epi16(x, _mm256_slli_si256(x, 4));
    x = _mm256_add_epi16(x, _mm256_slli_si256(x, 8));
    /* Broadcast lane 7 (top of low half) into all 8 lanes of high half;
       low half gets zero via -1 byte indices in shuffle_epi8. */
    {
        __m256i lo_in_both = _mm256_permute2x128_si256(x, x, 0x00);
        const __m256i bcast_pattern = _mm256_setr_epi8(
            (char)0x80,(char)0x80,(char)0x80,(char)0x80,
            (char)0x80,(char)0x80,(char)0x80,(char)0x80,
            (char)0x80,(char)0x80,(char)0x80,(char)0x80,
            (char)0x80,(char)0x80,(char)0x80,(char)0x80,
            14, 15, 14, 15, 14, 15, 14, 15,
            14, 15, 14, 15, 14, 15, 14, 15);
        __m256i bcast = _mm256_shuffle_epi8(lo_in_both, bcast_pattern);
        return _mm256_add_epi16(x, bcast);
    }
}

/* LOCAL pipeline: zigzag_dec → per-OutReg prefix sum → aggregate.
   Lane 0 of OutReg is the per-OutReg anchor (zigzag-encoded delta from 0).

   Ablation toggles (define at simdcomp build time to disable that step):
     ABLATE_ZIGZAG_LOCAL    — skip zigzag_dec
     ABLATE_PREFIXSUM_LOCAL — skip prefix_sum
   `aggregate_sums_u16` is always run (per the ablation spec: sum at the end
   after bitpacking completes). */
static __inline__ void agg_pipeline_local_simdcomp(__m256i OutReg, __m256i* sum) {
#ifndef ABLATE_ZIGZAG_LOCAL
    OutReg = zigzag_dec_u16_avx2(OutReg);
#endif
#ifndef ABLATE_PREFIXSUM_LOCAL
    OutReg = prefix_sum_u16_avx2(OutReg);
#endif
    aggregate_sums_u16(OutReg, sum);
}

/* CARRY pipeline: zigzag_dec → prefix_sum → +carry → update carry → aggregate.
   *carry is a scalar uint16_t holding the last decoded value (lane 15 of the
   previous OutReg). Stored scalar to avoid a 32-byte broadcast on every store;
   loaded via _mm256_set1_epi16 (vpbroadcastw) on use.

   Ablation toggles:
     ABLATE_ZIGZAG_CARRY     — skip zigzag_dec
     ABLATE_PREFIXSUM_CARRY  — skip prefix_sum
     ABLATE_CARRY_ADD        — skip the `OutReg + broadcast(*carry)` add
     ABLATE_BROADCAST_LANE15 — skip the scalar carry update (vpextrw lane 15)
                                (use with ABLATE_CARRY_ADD or with a stale *carry
                                 to isolate the extract cost vs. the carry-add)
   `aggregate_sums_u16` is always run.

   Note: with ABLATE_CARRY_ADD or ABLATE_BROADCAST_LANE15 set, decoded results
   are not meaningful — these are timing-only ablations. */
static __inline__ void agg_pipeline_carry_simdcomp(__m256i OutReg, uint16_t* carry,
                                                __m256i* sum) {
#ifndef ABLATE_ZIGZAG_CARRY
    OutReg = zigzag_dec_u16_avx2(OutReg);
#endif
#ifndef ABLATE_PREFIXSUM_CARRY
    OutReg = prefix_sum_u16_avx2(OutReg);
#endif
#ifndef ABLATE_CARRY_ADD
    OutReg = _mm256_add_epi16(OutReg, _mm256_set1_epi16((short)*carry));
#endif
#ifndef ABLATE_BROADCAST_LANE15
    *carry = (uint16_t)_mm256_extract_epi16(OutReg, 15);
#else
    (void)carry;
#endif
    aggregate_sums_u16(OutReg, sum);
}

""")

    return "\n".join(lines)


def gen_null_unpacker(I):
    block = I['block']
    return f"""\
static void SIMD_nullunpacker16(const {I['reg']} *_in, uint16_t *out) {{
  (void)_in;
  memset(out, 0, {block} * sizeof(uint16_t));
}}

"""


def gen_null_packer(I, name_suffix=""):
    return f"""\
static void __SIMD_fastpackwithoutmask0_16{name_suffix}(const uint16_t *_in, {I['reg']} *out) {{
  (void)out;
  (void)_in;
}}

"""


def gen_pack_function(bit, I, name_suffix=""):
    """Generate pack function for given bit width."""
    if bit == 0:
        return gen_null_packer(I, name_suffix)

    lines = []
    lanes = I['lanes']
    block = I['block']
    total_inputs = block // lanes

    lines.append(f"static void __SIMD_fastpackwithoutmask{bit}_16{name_suffix}("
                 f"const uint16_t *_in, {I['reg']} *out) {{")
    lines.append(f"  const {I['reg']} *in = (const {I['reg']} *)(_in);")

    if bit == LANE_BITS:
        lines.append(f"  {I['reg']} InReg = {I['load']}(in);")
        lines.append(f"  {I['store']}(out, InReg);")
        for i in range(1, total_inputs):
            lines.append(f"  InReg = {I['load']}(++in);")
            lines.append(f"  {I['store']}(out + {i}, InReg);")
        lines.append("}")
        lines.append("")
        return "\n".join(lines)

    lines.append(f"  {I['reg']} OutReg;")
    lines.append(f"  {I['reg']} InReg = {I['load']}(in);")
    lines.append("")

    out_word = 0
    bit_pos = 0

    lines.append("  OutReg = InReg;")
    bit_pos = bit

    for i in range(1, total_inputs):
        lines.append(f"  InReg = {I['load']}(++in);")

        remaining = LANE_BITS - bit_pos

        if remaining >= bit:
            if bit_pos == 0:
                lines.append("  OutReg = InReg;")
            else:
                lines.append(f"  OutReg = {I['or_fn']}(OutReg, {I['slli']}(InReg, {bit_pos}));")
            bit_pos += bit
        else:
            if remaining > 0:
                lines.append(f"  OutReg = {I['or_fn']}(OutReg, {I['slli']}(InReg, {bit_pos}));")
            lines.append(f"  {I['store']}(out + {out_word}, OutReg);")
            out_word += 1
            if remaining > 0:
                lines.append(f"  OutReg = {I['srli']}(InReg, {remaining});")
            else:
                lines.append("  OutReg = InReg;")
            bit_pos = bit - remaining

        if bit_pos == LANE_BITS:
            lines.append(f"  {I['store']}(out + {out_word}, OutReg);")
            out_word += 1
            bit_pos = 0

    if bit_pos > 0:
        lines.append(f"  {I['store']}(out + {out_word}, OutReg);")

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def gen_unpack_function(bit, I, mode='plain', name_suffix=''):
    """Generate fused unpack+sum function for given bit width.

    mode:
      'plain'              — aggregate_sums_u16(OutReg, sum)
      'delta_local'        — zigzag_dec → per-OutReg prefix sum → aggregate
      'delta_carry'        — zigzag_dec → prefix_sum → +carry → update carry → aggregate
      'corrected'          — OutReg += corrections[k] (per-OutReg array); aggregate.
                             Used by FoR-local/hierarchical and PFor corrected paths.
      'corrected_uniform'  — OutReg += anchor (single broadcast for all OutRegs); aggregate.
                             Used by FoR-global: one anchor per 256-elem sub-block.
    """
    assert mode in ('plain', 'delta_local', 'delta_carry', 'corrected', 'corrected_uniform')
    if bit == 0:
        return ""

    lines = []
    lanes = I['lanes']
    block = I['block']
    total_values = block // lanes

    suffix = {
        'plain': '',
        'delta_local': '_delta_local',
        'delta_carry': '_delta_carry',
        'corrected': '_corrected',
        'corrected_uniform': '_corrected_uniform',
    }[mode]
    needs_carry       = mode == 'delta_carry'
    needs_corrections = mode == 'corrected'
    needs_anchor      = mode == 'corrected_uniform'
    needs_outreg      = mode in ('corrected', 'corrected_uniform')

    extra_param = ""
    if needs_carry:
        extra_param = f", uint16_t *carry"
    elif needs_corrections:
        extra_param = f", const {I['reg']} *corrections"
    elif needs_anchor:
        extra_param = f", const {I['reg']} anchor"

    def agg_outreg(v):
        if mode == 'plain':
            return "  aggregate_sums_u16(OutReg, sum);"
        if mode == 'delta_local':
            return "  agg_pipeline_local_simdcomp(OutReg, sum);"
        if mode == 'delta_carry':
            return "  agg_pipeline_carry_simdcomp(OutReg, carry, sum);"
        if mode == 'corrected':
            return (f"  OutReg = _mm256_add_epi16(OutReg, corrections[{v}]);\n"
                    f"  aggregate_sums_u16(OutReg, sum);")
        # corrected_uniform:
        return ("  OutReg = _mm256_add_epi16(OutReg, anchor);\n"
                "  aggregate_sums_u16(OutReg, sum);")

    def agg_inreg(v):
        if mode == 'plain':
            return "  aggregate_sums_u16(InReg, sum);"
        if mode == 'delta_local':
            return "  agg_pipeline_local_simdcomp(InReg, sum);"
        if mode == 'delta_carry':
            return "  agg_pipeline_carry_simdcomp(InReg, carry, sum);"
        if mode == 'corrected':
            return (f"  OutReg = _mm256_add_epi16(InReg, corrections[{v}]);\n"
                    f"  aggregate_sums_u16(OutReg, sum);")
        # corrected_uniform: route through OutReg so we can add anchor.
        return ("  OutReg = _mm256_add_epi16(InReg, anchor);\n"
                "  aggregate_sums_u16(OutReg, sum);")

    lines.append(f"static void __SIMD_fastunpack{bit}_16{suffix}{name_suffix}("
                 f"const {I['reg']} *in, uint16_t *_out, {I['reg']}* sum{extra_param}) {{")
    lines.append("  (void)_out;")
    lines.append(f"  {I['reg']} InReg = {I['load']}(in);")
    lines.append(f"  {I['reg']} OutReg;")

    if bit == LANE_BITS:
        if not needs_outreg:
            lines.pop()  # remove OutReg — not needed for plain/delta modes
        lines.append(agg_inreg(0))
        for i in range(1, total_values):
            lines.append(f"  InReg = {I['load']}(++in);")
            lines.append(agg_inreg(i))
        lines.append("}")
        lines.append("")
        return "\n".join(lines)

    lines.append(f"  const {I['reg']} mask = {I['set1']}((1U << {bit}) - 1);")
    lines.append("")

    bit_pos = 0

    for v in range(total_values):
        remaining = LANE_BITS - bit_pos

        if remaining >= bit:
            if bit_pos == 0:
                lines.append(f"  OutReg = {I['and_fn']}(InReg, mask);")
            else:
                lines.append(f"  OutReg = {I['and_fn']}({I['srli']}(InReg, {bit_pos}), mask);")
            lines.append(agg_outreg(v))
            lines.append("")
            bit_pos += bit
        else:
            if remaining > 0:
                lines.append(f"  OutReg = {I['srli']}(InReg, {bit_pos});")
            lines.append(f"  InReg = {I['load']}(++in);")

            need = bit - remaining
            if remaining > 0:
                lines.append("  OutReg =")
                lines.append(f"      {I['or_fn']}(OutReg, {I['and_fn']}({I['slli']}(InReg, {bit} - {need}), mask));")
            else:
                lines.append(f"  OutReg = {I['and_fn']}(InReg, mask);")
            lines.append(agg_outreg(v))
            lines.append("")
            bit_pos = need

        if bit_pos == LANE_BITS:
            if v < total_values - 1:
                lines.append(f"  InReg = {I['load']}(++in);")
            bit_pos = 0

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def gen_pack_dispatcher(I):
    lines = []
    lines.append(f"void simdpack_u16(const uint16_t *in, {I['reg']} *out, const uint32_t bit) {{")
    lines.append("  switch (bit) {")
    for b in range(MAX_BIT + 1):
        lines.append(f"  case {b}:")
        lines.append(f"    __SIMD_fastpackwithoutmask{b}_16(in, out);")
        lines.append("    return;")
        lines.append("")
    lines.append("  default:")
    lines.append("    break;")
    lines.append("  }")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def gen_unpack_dispatcher(I):
    lines = []
    lines.append(f"void simdunpack_u16(const {I['reg']} *in, uint16_t *out, "
                 f"const uint32_t bit, {I['reg']}* sum) {{")
    lines.append("  switch (bit) {")
    lines.append("  case 0:")
    lines.append("    SIMD_nullunpacker16(in, out);")
    lines.append("    break;")
    lines.append("")
    for b in range(1, MAX_BIT + 1):
        lines.append(f"  case {b}:")
        lines.append(f"    __SIMD_fastunpack{b}_16(in, out, sum);")
        lines.append("    break;")
        lines.append("")
    lines.append("  default:")
    lines.append("    break;")
    lines.append("  }")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def gen_unpack_dispatcher_delta_local(I):
    block = I['block']
    lanes = I['lanes']
    outregs = block // lanes
    lines = []
    lines.append(f"void simdunpack_u16_delta_local(const {I['reg']} *in, "
                 f"uint16_t *out, const uint32_t bit, {I['reg']}* sum) {{")
    lines.append("  switch (bit) {")
    lines.append("  case 0:")
    lines.append("    /* b==0: every value is 0, delta-decoded prefix-sums are all 0. */")
    lines.append("    SIMD_nullunpacker16(in, out);")
    lines.append("    break;")
    lines.append("")
    for b in range(1, MAX_BIT + 1):
        lines.append(f"  case {b}:")
        lines.append(f"    __SIMD_fastunpack{b}_16_delta_local(in, out, sum);")
        lines.append("    break;")
        lines.append("")
    lines.append("  default:")
    lines.append("    break;")
    lines.append("  }")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def gen_unpack_dispatcher_delta_carry(I):
    block = I['block']
    lanes = I['lanes']
    outregs = block // lanes
    lines = []
    lines.append(f"void simdunpack_u16_delta_carry(const {I['reg']} *in, "
                 f"uint16_t *out, const uint32_t bit, uint16_t *carry, "
                 f"{I['reg']}* sum) {{")
    lines.append("  switch (bit) {")
    lines.append("  case 0: {")
    lines.append("    /* b==0: every value is 0 (= zigzag delta of 0 from prev); */")
    lines.append("    /* prefix sums of zeros yield carry repeated; carry is unchanged. */")
    lines.append("    size_t i;")
    lines.append(f"    for (i = 0; i < {outregs}; ++i) {{")
    lines.append(f"      agg_pipeline_carry_simdcomp(_mm256_setzero_si256(), carry, sum);")
    lines.append("    }")
    lines.append("    break;")
    lines.append("  }")
    lines.append("")
    for b in range(1, MAX_BIT + 1):
        lines.append(f"  case {b}:")
        lines.append(f"    __SIMD_fastunpack{b}_16_delta_carry(in, out, sum, carry);")
        lines.append("    break;")
        lines.append("")
    lines.append("  default:")
    lines.append("    break;")
    lines.append("  }")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def gen_unpack_dispatcher_corrected(I):
    block = I['block']
    lanes = I['lanes']
    outregs = block // lanes
    lines = []
    lines.append(f"void simdunpack_u16_corrected(const {I['reg']} *in, "
                 f"uint16_t *out, const uint32_t bit, "
                 f"const {I['reg']} *corrections, {I['reg']}* sum) {{")
    lines.append("  switch (bit) {")
    lines.append("  case 0:")
    lines.append("    /* b==0: every unpacked OutReg is 0; the corrected OutReg")
    lines.append("       is corrections[k], so we aggregate the corrections.")
    lines.append("       (FoR codecs land here when the residual stream is constant 0.) */")
    lines.append("    {")
    lines.append(f"      size_t _k;")
    lines.append(f"      for (_k = 0; _k < {outregs}; ++_k) {{")
    lines.append(f"        aggregate_sums_u16(corrections[_k], sum);")
    lines.append("      }")
    lines.append("    }")
    lines.append("    SIMD_nullunpacker16(in, out);")
    lines.append("    break;")
    lines.append("")
    for b in range(1, MAX_BIT + 1):
        lines.append(f"  case {b}:")
        lines.append(f"    __SIMD_fastunpack{b}_16_corrected(in, out, sum, corrections);")
        lines.append("    break;")
        lines.append("")
    lines.append("  default:")
    lines.append("    break;")
    lines.append("  }")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def gen_unpack_dispatcher_corrected_uniform(I):
    block = I['block']
    lanes = I['lanes']
    outregs = block // lanes
    lines = []
    lines.append(f"void simdunpack_u16_corrected_uniform(const {I['reg']} *in, "
                 f"uint16_t *out, const uint32_t bit, "
                 f"const {I['reg']} anchor, {I['reg']}* sum) {{")
    lines.append("  switch (bit) {")
    lines.append("  case 0:")
    lines.append("    /* b==0: every unpacked OutReg is 0; corrected OutReg = anchor.")
    lines.append("       Aggregate anchor once per OutReg. */")
    lines.append("    {")
    lines.append(f"      size_t _k;")
    lines.append(f"      for (_k = 0; _k < {outregs}; ++_k) {{")
    lines.append(f"        aggregate_sums_u16(anchor, sum);")
    lines.append("      }")
    lines.append("    }")
    lines.append("    SIMD_nullunpacker16(in, out);")
    lines.append("    break;")
    lines.append("")
    for b in range(1, MAX_BIT + 1):
        lines.append(f"  case {b}:")
        lines.append(f"    __SIMD_fastunpack{b}_16_corrected_uniform(in, out, sum, anchor);")
        lines.append("    break;")
        lines.append("")
    lines.append("  default:")
    lines.append("    break;")
    lines.append("  }")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def gen_pack_dispatcher_nW(I, W, name_suffix):
    lines = []
    lines.append(f"void simdpack_u16_n{W}(const uint16_t *in, {I['reg']} *out, const uint32_t bit) {{")
    lines.append("  switch (bit) {")
    for b in range(MAX_BIT + 1):
        lines.append(f"  case {b}:")
        lines.append(f"    __SIMD_fastpackwithoutmask{b}_16{name_suffix}(in, out);")
        lines.append("    return;")
        lines.append("")
    lines.append("  default:")
    lines.append("    break;")
    lines.append("  }")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def gen_unpack_dispatcher_corrected_uniform_nW(I, W, name_suffix):
    n_outreg = W // I['lanes']
    lines = []
    lines.append(f"void simdunpack_u16_corrected_uniform_n{W}(const {I['reg']} *in, uint16_t *out,")
    lines.append(f"    const uint32_t bit, const {I['reg']} anchor, {I['reg']}* sum) {{")
    lines.append("  switch (bit) {")
    lines.append("  case 0:")
    lines.append("    /* b==0: every unpacked OutReg is 0; corrected OutReg = anchor. */")
    lines.append("    {")
    lines.append(f"      size_t _k;")
    lines.append(f"      for (_k = 0; _k < {n_outreg}; ++_k) {{")
    lines.append(f"        aggregate_sums_u16(anchor, sum);")
    lines.append("      }")
    lines.append("    }")
    lines.append("    (void)in; (void)out;")
    lines.append("    break;")
    lines.append("")
    for b in range(1, MAX_BIT + 1):
        lines.append(f"  case {b}:")
        lines.append(f"    __SIMD_fastunpack{b}_16_corrected_uniform{name_suffix}(in, out, sum, anchor);")
        lines.append("    return;")
        lines.append("")
    lines.append("  default:")
    lines.append("    break;")
    lines.append("  }")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def gen_shortlength_pack(I):
    lanes = I['lanes']
    return f"""\
{I['reg']} *simdpack_shortlength_u16(const uint16_t *in, int length, {I['reg']} *out,
                                   const uint32_t bit) {{
  int k;
  int inwordpointer;
  {I['reg']} P;
  uint32_t firstpass;
  if (bit == 0)
    return out;
  if (bit == 16) {{
    memcpy(out, in, length * sizeof(uint16_t));
    return ({I['reg']} *)((uint16_t *)out + length);
  }}
  inwordpointer = 0;
  P = {I['setzero']}();
  for (k = 0; k < length / {lanes}; ++k) {{
    {I['reg']} value = {I['load']}(((const {I['reg']} *)in + k));
    P = {I['or_fn']}(P, {I['slli']}(value, inwordpointer));
    firstpass = 16 - inwordpointer;
    if (bit < firstpass) {{
      inwordpointer += bit;
    }} else {{
      {I['store']}(out++, P);
      P = {I['srli']}(value, firstpass);
      inwordpointer = bit - firstpass;
    }}
  }}
  if (length % {lanes} != 0) {{
    uint16_t buffer[{lanes}];
    {I['reg']} value;
    for (k = 0; k < (length % {lanes}); ++k) {{
      buffer[k] = in[length / {lanes} * {lanes} + k];
    }}
    for (k = (length % {lanes}); k < {lanes}; ++k) {{
      buffer[k] = 0;
    }}
    value = {I['load']}(({I['reg']} *)buffer);
    P = {I['or_fn']}(P, {I['slli']}(value, inwordpointer));
    firstpass = 16 - inwordpointer;
    if (bit < firstpass) {{
      inwordpointer += bit;
    }} else {{
      {I['store']}(out++, P);
      P = {I['srli']}(value, firstpass);
      inwordpointer = bit - firstpass;
    }}
  }}
  if (inwordpointer != 0) {{
    {I['store']}(out++, P);
  }}
  return out;
}}

"""


def gen_shortlength_unpack(I):
    lanes = I['lanes']
    return f"""\
const {I['reg']} *simdunpack_shortlength_u16(const {I['reg']} *in, int length,
                                           uint16_t *out, const uint32_t bit) {{
  int k;
  {I['reg']} maskbits;
  int inwordpointer;
  {I['reg']} P;
  if (length == 0)
    return in;
  if (bit == 0) {{
    for (k = 0; k < length; ++k) {{
      out[k] = 0;
    }}
    return in;
  }}
  if (bit == 16) {{
    memcpy(out, in, length * sizeof(uint16_t));
    return (const {I['reg']} *)((uint16_t *)in + length);
  }}
  maskbits = {I['set1']}((1U << bit) - 1);
  inwordpointer = 0;
  P = {I['load']}(({I['reg']} *)in);
  ++in;
  if (length % {lanes} == 0) {{
    for (k = 0; k + 1 < length / {lanes}; ++k) {{
      {I['reg']} answer = {I['srli']}(P, inwordpointer);
      const uint32_t firstpass = 16 - inwordpointer;
      if (bit < firstpass) {{
        inwordpointer += bit;
      }} else {{
        P = {I['load']}(({I['reg']} *)in);
        ++in;
        answer = {I['or_fn']}({I['slli']}(P, firstpass), answer);
        inwordpointer = bit - firstpass;
      }}
      answer = {I['and_fn']}(maskbits, answer);
      {I['store']}(({I['reg']} *)out, answer);
      out += {lanes};
    }}
    if (k < length / {lanes}) {{
      {I['reg']} answer = {I['srli']}(P, inwordpointer);
      const uint32_t firstpass = 16 - inwordpointer;
      if (bit < firstpass) {{
        inwordpointer += bit;
      }} else if (bit == firstpass) {{
        inwordpointer = 0;
      }} else {{
        P = {I['load']}(({I['reg']} *)in);
        ++in;
        answer = {I['or_fn']}({I['slli']}(P, firstpass), answer);
        inwordpointer = bit - firstpass;
      }}
      answer = {I['and_fn']}(maskbits, answer);
      {I['store']}(({I['reg']} *)out, answer);
      out += {lanes};
    }}
  }} else {{
    for (k = 0; k < length / {lanes}; ++k) {{
      {I['reg']} answer = {I['srli']}(P, inwordpointer);
      const uint32_t firstpass = 16 - inwordpointer;
      if (bit < firstpass) {{
        inwordpointer += bit;
      }} else {{
        P = {I['load']}(({I['reg']} *)in);
        ++in;
        answer = {I['or_fn']}({I['slli']}(P, firstpass), answer);
        inwordpointer = bit - firstpass;
      }}
      answer = {I['and_fn']}(maskbits, answer);
      {I['store']}(({I['reg']} *)out, answer);
      out += {lanes};
    }}
    uint16_t buffer[{lanes}];
    {I['reg']} answer = {I['srli']}(P, inwordpointer);
    const uint32_t firstpass = 16 - inwordpointer;
    if (bit < firstpass) {{
      inwordpointer += bit;
    }} else if (bit == firstpass) {{
      inwordpointer = 0;
    }} else {{
      P = {I['load']}(({I['reg']} *)in);
      ++in;
      answer = {I['or_fn']}({I['slli']}(P, firstpass), answer);
      inwordpointer = bit - firstpass;
    }}
    answer = {I['and_fn']}(maskbits, answer);
    {I['store']}(({I['reg']} *)buffer, answer);
    for (k = 0; k < (length % {lanes}); ++k) {{
      *out = buffer[k];
      ++out;
    }}
  }}
  return in;
}}

"""


def gen_utility_functions(I):
    width = I['width']
    lanes = I['lanes']
    block = I['block']

    if width == 128:
        oras_body = f"""\
/* returns the integer logarithm of v (bit width) for uint16 */
static uint32_t bits_u16(const uint16_t v) {{
  return v == 0 ? 0 : 32 - __builtin_clz((uint32_t)v);
}}

static uint32_t oras_u16(const {I['reg']} accumulator) {{
  /* Horizontal OR of {lanes} uint16 lanes into a single uint16 value */
  const {I['reg']} _tmp1 = {I['or_fn']}(
      _mm_srli_si128(accumulator, 8), accumulator);
  const {I['reg']} _tmp2 = {I['or_fn']}(
      _mm_srli_si128(_tmp1, 4), _tmp1);
  const {I['reg']} _tmp3 = {I['or_fn']}(
      _mm_srli_si128(_tmp2, 2), _tmp2);
  return (uint16_t)_mm_extract_epi16(_tmp3, 0);
}}
"""
    else:
        oras_body = f"""\
/* returns the integer logarithm of v (bit width) for uint16 */
static uint32_t bits_u16(const uint16_t v) {{
  return v == 0 ? 0 : 32 - __builtin_clz((uint32_t)v);
}}

static uint32_t oras_u16(const {I['reg']} accumulator) {{
  /* Horizontal OR of {lanes} uint16 lanes into a single uint16 value */
  __m128i lo = _mm256_castsi256_si128(accumulator);
  __m128i hi = _mm256_extracti128_si256(accumulator, 1);
  __m128i combined = _mm_or_si128(lo, hi);
  const __m128i _tmp1 = _mm_or_si128(
      _mm_srli_si128(combined, 8), combined);
  const __m128i _tmp2 = _mm_or_si128(
      _mm_srli_si128(_tmp1, 4), _tmp1);
  const __m128i _tmp3 = _mm_or_si128(
      _mm_srli_si128(_tmp2, 2), _tmp2);
  return (uint16_t)_mm_extract_epi16(_tmp3, 0);
}}
"""

    if width == 128:
        hsum = """\
  /* Horizontal reduction: 4 x int32 -> 1 x int32 */
  __m128i s = sum;
  s = _mm_add_epi32(s, _mm_shuffle_epi32(s, _MM_SHUFFLE(1,0,3,2)));
  s = _mm_add_epi32(s, _mm_shuffle_epi32(s, _MM_SHUFFLE(2,3,0,1)));

  uint32_t finalsum = (uint32_t)_mm_cvtsi128_si32(s);"""
    else:
        hsum = """\
  /* 256-bit horizontal reduction */
  __m128i lo = _mm256_castsi256_si128(sum);
  __m128i hi = _mm256_extracti128_si256(sum, 1);
  __m128i s = _mm_add_epi32(lo, hi);
  s = _mm_add_epi32(s, _mm_shuffle_epi32(s, _MM_SHUFFLE(1,0,3,2)));
  s = _mm_add_epi32(s, _mm_shuffle_epi32(s, _MM_SHUFFLE(2,3,0,1)));

  uint32_t finalsum = (uint32_t)_mm_cvtsi128_si32(s);"""

    if width == 256:
        delta_length = f"""\
/* LOCAL delta variant: SIMD blocks run zigzag_dec + per-OutReg prefix sum +
   aggregate (no inter-OutReg carry). Tail does scalar zigzag-decode + prefix
   sum, with prev resetting every 16 elements (rounded_length is a multiple
   of 16 so the tail starts at a 16-boundary). */
const {I['reg']} *simdunpack_length_u16_delta_local(const {I['reg']} *in,
                                                  size_t length, uint16_t *out,
                                                  const uint32_t bit,
                                                  uint32_t *outsum) {{
  {I['reg']} sum = {I['setzero']}();
  size_t k;
  for (k = 0; k < length / SIMDBlockSize_u16; ++k) {{
    simdunpack_u16_delta_local(in, out, bit, &sum);
    out += SIMDBlockSize_u16;
    in += bit;
  }}
{hsum}

  /* Tail: scalar un-zigzag + un-delta with prev resetting every 16 elements. */
  size_t remainder = length % SIMDBlockSize_u16;
  if (remainder > 0) {{
    in = simdunpack_shortlength_u16(in, remainder, out, bit);
    uint16_t prev = 0;
    size_t i;
    for (i = 0; i < remainder; ++i) {{
      if ((i & 15) == 0) prev = 0;
      uint16_t delta = ZigzagDec16_simdcomp(out[i]);
      uint16_t cur = (uint16_t)(prev + delta);
      finalsum += cur;
      prev = cur;
    }}
  }}
  *outsum = finalsum;
  return in;
}}

/* CARRY delta variant: SIMD blocks thread a broadcast-carry __m256i across
   OutRegs/blocks. Tail scalar continues the chain by seeding prev from the
   last broadcast-carry value. */
const {I['reg']} *simdunpack_length_u16_delta_carry(const {I['reg']} *in,
                                                  size_t length, uint16_t *out,
                                                  const uint32_t bit,
                                                  uint32_t *outsum) {{
  {I['reg']} sum = {I['setzero']}();
  uint16_t carry = 0;
  size_t k;
  for (k = 0; k < length / SIMDBlockSize_u16; ++k) {{
    simdunpack_u16_delta_carry(in, out, bit, &carry, &sum);
    out += SIMDBlockSize_u16;
    in += bit;
  }}
{hsum}

  /* Tail: scalar un-zigzag + un-delta seeded from the scalar carry. */
  size_t remainder = length % SIMDBlockSize_u16;
  if (remainder > 0) {{
    in = simdunpack_shortlength_u16(in, remainder, out, bit);
    uint16_t prev = carry;
    size_t i;
    for (i = 0; i < remainder; ++i) {{
      uint16_t delta = ZigzagDec16_simdcomp(out[i]);
      uint16_t cur = (uint16_t)(prev + delta);
      finalsum += cur;
      prev = cur;
    }}
  }}
  *outsum = finalsum;
  return in;
}}

"""
    else:
        delta_length = ""

    return f"""\
{oras_body}

uint32_t maxbits_length_u16(const uint16_t *in, size_t length) {{
  size_t k;
  size_t lengthdividedby{lanes} = length / {lanes};
  size_t offset = lengthdividedby{lanes} * {lanes};
  uint32_t bigxor = 0;
  if (lengthdividedby{lanes} > 0) {{
    const {I['reg']} *pin = (const {I['reg']} *)(in);
    {I['reg']} accumulator = {I['load']}(pin);
    k = 1;
    for (; {lanes} * k < {lanes} * lengthdividedby{lanes}; ++k) {{
      {I['reg']} newvec = {I['load']}(pin + k);
      accumulator = {I['or_fn']}(accumulator, newvec);
    }}
    bigxor = oras_u16(accumulator);
  }}
  for (k = offset; k < length; ++k)
    bigxor |= in[k];
  return bits_u16((uint16_t)bigxor);
}}

int simdpack_compressedbytes_u16(int length, const uint32_t bit) {{
  if (bit == 0)
    return 0;
  if (bit == 16) {{
    return length * sizeof(uint16_t);
  }}
  /* Each group of {lanes} uint16 lanes packs to ({lanes} * bit) bits = bit bytes per group.
     Total groups = (length + {lanes - 1}) / {lanes}.  Round up to {I['reg']} boundary. */
  return (((length + {lanes - 1}) / {lanes}) * bit + 15) / 16 * sizeof({I['reg']});
}}

{I['reg']} *simdpack_length_u16(const uint16_t *in, size_t length, {I['reg']} *out,
                              const uint32_t bit) {{
  size_t k;
  for (k = 0; k < length / SIMDBlockSize_u16; ++k) {{
    simdpack_u16(in, out, bit);
    in += SIMDBlockSize_u16;
    out += bit;
  }}
  return simdpack_shortlength_u16(in, length % SIMDBlockSize_u16, out, bit);
}}

const {I['reg']} *simdunpack_length_u16(const {I['reg']} *in, size_t length,
                                      uint16_t *out, const uint32_t bit,
                                      uint32_t *outsum) {{
  {I['reg']} sum = {I['setzero']}();
  size_t k;
  for (k = 0; k < length / SIMDBlockSize_u16; ++k) {{
    simdunpack_u16(in, out, bit, &sum);
    out += SIMDBlockSize_u16;
    in += bit;
  }}
{hsum}

  /* Handle remainder with scalar sum */
  size_t remainder = length % SIMDBlockSize_u16;
  if (remainder > 0) {{
    in = simdunpack_shortlength_u16(in, remainder, out, bit);
    size_t i;
    for (i = 0; i < remainder; ++i) {{
      finalsum += out[i];
    }}
  }}
  *outsum = finalsum;
  return in;
}}

{delta_length}"""


def main():
    parser = argparse.ArgumentParser(
        description='Generate SIMD bit-packing for uint16')
    parser.add_argument('--width', type=int, choices=[128, 256], default=128,
                        help='Register width in bits (128=AVX, 256=AVX2)')
    args = parser.parse_args()

    I = intrinsics(args.width)
    lanes = args.width // LANE_BITS
    block = lanes * MAX_BIT  # 128 for 128-bit, 256 for 256-bit
    I['lanes'] = lanes
    I['block'] = block
    I['width'] = args.width

    out = []
    out.append(gen_header(I))
    out.append(gen_null_unpacker(I))

    # Pack functions for all bit widths
    for bit in range(MAX_BIT + 1):
        out.append(gen_pack_function(bit, I))

    out.append(gen_pack_dispatcher(I))

    # Unpack+sum functions for all bit widths
    for bit in range(1, MAX_BIT + 1):
        out.append(gen_unpack_function(bit, I, mode='plain'))

    out.append(gen_unpack_dispatcher(I))

    # AVX2-only: delta-local and delta-carry unpack functions + dispatchers.
    if I['width'] == 256:
        for bit in range(1, MAX_BIT + 1):
            out.append(gen_unpack_function(bit, I, mode='delta_local'))
        out.append(gen_unpack_dispatcher_delta_local(I))

        for bit in range(1, MAX_BIT + 1):
            out.append(gen_unpack_function(bit, I, mode='delta_carry'))
        out.append(gen_unpack_dispatcher_delta_carry(I))

        for bit in range(1, MAX_BIT + 1):
            out.append(gen_unpack_function(bit, I, mode='corrected'))
        out.append(gen_unpack_dispatcher_corrected(I))

        for bit in range(1, MAX_BIT + 1):
            out.append(gen_unpack_function(bit, I, mode='corrected_uniform'))
        out.append(gen_unpack_dispatcher_corrected_uniform(I))

    # Sub-block variants for W=128 (8 OutRegs): pack + corrected_uniform unpack.
    # Only generated for AVX2 (256-bit) since the FoR-global codecs are AVX2-only.
    if I['width'] == 256:
        for W in [32, 64, 128]:
          name_suffix = f'_n{W}'
          I_sub = dict(I, block=W)
          for bit in range(MAX_BIT + 1):
              out.append(gen_pack_function(bit, I_sub, name_suffix=name_suffix))
          for bit in range(1, MAX_BIT + 1):
              out.append(gen_unpack_function(bit, I_sub, mode='corrected_uniform',
                                             name_suffix=name_suffix))
          out.append(gen_pack_dispatcher_nW(I_sub, W, name_suffix))
          out.append(gen_unpack_dispatcher_corrected_uniform_nW(I_sub, W, name_suffix))

    # Short-length handlers
    out.append(gen_shortlength_pack(I))
    out.append(gen_shortlength_unpack(I))

    # Utility functions
    out.append(gen_utility_functions(I))

    script_dir = os.path.dirname(os.path.abspath(__file__))
    src_dir = os.path.join(script_dir, '..', 'src')
    out_path = os.path.join(src_dir, 'simdbitpacking_u16.c')

    with open(out_path, 'w') as f:
        f.write("".join(out))
    print(f"Generated {out_path}")


if __name__ == "__main__":
    main()
