#!/usr/bin/env python3
"""
Generate simdbitpacking_u16.c — SIMD bit-packing/unpacking for uint16,
with fused sum aggregation (no output writes during unpack).

Supports 128-bit (AVX) and 256-bit (AVX2) register widths.

Usage:
  python gen_simdbitpacking_u16.py --width 128   # AVX (128-bit registers)
  python gen_simdbitpacking_u16.py --width 256   # AVX2 (256-bit registers)
"""
import argparse
import os
import sys

LANE_BITS = 16
MAX_BIT = 16


def intrinsics(width):
    """Return a dict of intrinsic names for the given register width."""
    if width == 128:
        return dict(
            reg='__m128i',
            load='_mm_loadu_si128',
            store='_mm_storeu_si128',
            setzero='_mm_setzero_si128',
            or_fn='_mm_or_si128',
            and_fn='_mm_and_si128',
            slli='_mm_slli_epi16',
            srli='_mm_srli_epi16',
            set1='_mm_set1_epi16',
            add='_mm_add_epi32',
            unpacklo='_mm_unpacklo_epi16',
            unpackhi='_mm_unpackhi_epi16',
            srli_bytes='_mm_srli_si128',
            extract16='_mm_extract_epi16',
        )
    else:
        return dict(
            reg='__m256i',
            load='_mm256_loadu_si256',
            store='_mm256_storeu_si256',
            setzero='_mm256_setzero_si256',
            or_fn='_mm256_or_si256',
            and_fn='_mm256_and_si256',
            slli='_mm256_slli_epi16',
            srli='_mm256_srli_epi16',
            set1='_mm256_set1_epi16',
            add='_mm256_add_epi32',
            unpacklo='_mm256_unpacklo_epi16',
            unpackhi='_mm256_unpackhi_epi16',
        )


def gen_header(I):
    width = I['width']
    lines = []
    lines.append(f"""\
/**
 * Auto-generated uint16 SIMD bit-packing with fused sum aggregation.
 * Generated by gen_simdbitpacking_u16.py (width={width})
 *
 * This code is released under a BSD License.
 */
#include "simdbitpacking_u16.h"
#include <string.h>
""")

    block = I['block']
    lanes = I['lanes']

    lines.append(f"#define SIMDBlockSize_u16 {block}")
    lines.append("")

    if width == 128:
        lines.append(f"static const {I['reg']} kZero = {{0, 0}};")
    else:
        lines.append(f"static const {I['reg']} kZero = {{0, 0, 0, 0}};")
    lines.append("")

    lines.append(f"static void aggregate_sums_u16({I['reg']} OutReg, {I['reg']}* sum) {{")
    lines.append(f"    /* Zero-extend 8 x uint16 -> 4 x int32, then accumulate.")
    lines.append(f"       _mm_madd_epi16 treats inputs as signed — wrong for values > 32767.")
    lines.append(f"       3 instructions / 8 values = 0.375 inst/val. */")
    lines.append(f"    *sum = {I['add']}(*sum, {I['unpacklo']}(OutReg, kZero));")
    lines.append(f"    *sum = {I['add']}(*sum, {I['unpackhi']}(OutReg, kZero));")
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def gen_null_unpacker(I):
    block = I['block']
    return f"""\
static void SIMD_nullunpacker16(const {I['reg']} *_in, uint16_t *out) {{
  (void)_in;
  memset(out, 0, {block} * sizeof(uint16_t));
}}

"""


def gen_null_packer(I):
    return f"""\
static void __SIMD_fastpackwithoutmask0_16(const uint16_t *_in, {I['reg']} *out) {{
  (void)out;
  (void)_in;
}}

"""


def gen_pack_function(bit, I):
    """Generate pack function for given bit width."""
    if bit == 0:
        return gen_null_packer(I)

    lines = []
    lanes = I['lanes']
    block = I['block']
    total_inputs = block // lanes

    lines.append(f"static void __SIMD_fastpackwithoutmask{bit}_16("
                 f"const uint16_t *_in, {I['reg']} *out) {{")
    lines.append(f"  const {I['reg']} *in = (const {I['reg']} *)(_in);")

    if bit == LANE_BITS:
        lines.append(f"  {I['reg']} InReg = {I['load']}(in);")
        lines.append(f"  {I['store']}(out, InReg);")
        for i in range(1, total_inputs):
            lines.append(f"  InReg = {I['load']}(++in);")
            lines.append(f"  {I['store']}(out + {i}, InReg);")
        lines.append("}")
        lines.append("")
        return "\n".join(lines)

    lines.append(f"  {I['reg']} OutReg;")
    lines.append(f"  {I['reg']} InReg = {I['load']}(in);")
    lines.append("")

    out_word = 0
    bit_pos = 0

    lines.append("  OutReg = InReg;")
    bit_pos = bit

    for i in range(1, total_inputs):
        lines.append(f"  InReg = {I['load']}(++in);")

        remaining = LANE_BITS - bit_pos

        if remaining >= bit:
            if bit_pos == 0:
                lines.append("  OutReg = InReg;")
            else:
                lines.append(f"  OutReg = {I['or_fn']}(OutReg, {I['slli']}(InReg, {bit_pos}));")
            bit_pos += bit
        else:
            if remaining > 0:
                lines.append(f"  OutReg = {I['or_fn']}(OutReg, {I['slli']}(InReg, {bit_pos}));")
            lines.append(f"  {I['store']}(out + {out_word}, OutReg);")
            out_word += 1
            if remaining > 0:
                lines.append(f"  OutReg = {I['srli']}(InReg, {remaining});")
            else:
                lines.append("  OutReg = InReg;")
            bit_pos = bit - remaining

        if bit_pos == LANE_BITS:
            lines.append(f"  {I['store']}(out + {out_word}, OutReg);")
            out_word += 1
            bit_pos = 0

    if bit_pos > 0:
        lines.append(f"  {I['store']}(out + {out_word}, OutReg);")

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def gen_unpack_function(bit, I):
    """Generate fused unpack+sum function for given bit width."""
    if bit == 0:
        return ""

    lines = []
    lanes = I['lanes']
    block = I['block']
    total_values = block // lanes

    lines.append(f"static void __SIMD_fastunpack{bit}_16("
                 f"const {I['reg']} *in, uint16_t *_out, {I['reg']}* sum) {{")
    lines.append("  (void)_out;")
    lines.append(f"  {I['reg']} InReg = {I['load']}(in);")
    lines.append(f"  {I['reg']} OutReg;")

    if bit == LANE_BITS:
        lines.pop()  # remove OutReg
        lines.append("  aggregate_sums_u16(InReg, sum);")
        for i in range(1, total_values):
            lines.append(f"  InReg = {I['load']}(++in);")
            lines.append("  aggregate_sums_u16(InReg, sum);")
        lines.append("}")
        lines.append("")
        return "\n".join(lines)

    lines.append(f"  const {I['reg']} mask = {I['set1']}((1U << {bit}) - 1);")
    lines.append("")

    bit_pos = 0

    for v in range(total_values):
        remaining = LANE_BITS - bit_pos

        if remaining >= bit:
            if bit_pos == 0:
                lines.append(f"  OutReg = {I['and_fn']}(InReg, mask);")
            else:
                lines.append(f"  OutReg = {I['and_fn']}({I['srli']}(InReg, {bit_pos}), mask);")
            lines.append("  aggregate_sums_u16(OutReg, sum);")
            lines.append("")
            bit_pos += bit
        else:
            if remaining > 0:
                lines.append(f"  OutReg = {I['srli']}(InReg, {bit_pos});")
            lines.append(f"  InReg = {I['load']}(++in);")

            need = bit - remaining
            if remaining > 0:
                lines.append("  OutReg =")
                lines.append(f"      {I['or_fn']}(OutReg, {I['and_fn']}({I['slli']}(InReg, {bit} - {need}), mask));")
            else:
                lines.append(f"  OutReg = {I['and_fn']}(InReg, mask);")
            lines.append("  aggregate_sums_u16(OutReg, sum);")
            lines.append("")
            bit_pos = need

        if bit_pos == LANE_BITS:
            if v < total_values - 1:
                lines.append(f"  InReg = {I['load']}(++in);")
            bit_pos = 0

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def gen_pack_dispatcher(I):
    lines = []
    lines.append(f"void simdpack_u16(const uint16_t *in, {I['reg']} *out, const uint32_t bit) {{")
    lines.append("  switch (bit) {")
    for b in range(MAX_BIT + 1):
        lines.append(f"  case {b}:")
        lines.append(f"    __SIMD_fastpackwithoutmask{b}_16(in, out);")
        lines.append("    return;")
        lines.append("")
    lines.append("  default:")
    lines.append("    break;")
    lines.append("  }")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def gen_unpack_dispatcher(I):
    lines = []
    lines.append(f"void simdunpack_u16(const {I['reg']} *in, uint16_t *out, "
                 f"const uint32_t bit, {I['reg']}* sum) {{")
    lines.append("  switch (bit) {")
    lines.append("  case 0:")
    lines.append("    SIMD_nullunpacker16(in, out);")
    lines.append("    break;")
    lines.append("")
    for b in range(1, MAX_BIT + 1):
        lines.append(f"  case {b}:")
        lines.append(f"    __SIMD_fastunpack{b}_16(in, out, sum);")
        lines.append("    break;")
        lines.append("")
    lines.append("  default:")
    lines.append("    break;")
    lines.append("  }")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def gen_shortlength_pack(I):
    lanes = I['lanes']
    return f"""\
{I['reg']} *simdpack_shortlength_u16(const uint16_t *in, int length, {I['reg']} *out,
                                   const uint32_t bit) {{
  int k;
  int inwordpointer;
  {I['reg']} P;
  uint32_t firstpass;
  if (bit == 0)
    return out;
  if (bit == 16) {{
    memcpy(out, in, length * sizeof(uint16_t));
    return ({I['reg']} *)((uint16_t *)out + length);
  }}
  inwordpointer = 0;
  P = {I['setzero']}();
  for (k = 0; k < length / {lanes}; ++k) {{
    {I['reg']} value = {I['load']}(((const {I['reg']} *)in + k));
    P = {I['or_fn']}(P, {I['slli']}(value, inwordpointer));
    firstpass = 16 - inwordpointer;
    if (bit < firstpass) {{
      inwordpointer += bit;
    }} else {{
      {I['store']}(out++, P);
      P = {I['srli']}(value, firstpass);
      inwordpointer = bit - firstpass;
    }}
  }}
  if (length % {lanes} != 0) {{
    uint16_t buffer[{lanes}];
    {I['reg']} value;
    for (k = 0; k < (length % {lanes}); ++k) {{
      buffer[k] = in[length / {lanes} * {lanes} + k];
    }}
    for (k = (length % {lanes}); k < {lanes}; ++k) {{
      buffer[k] = 0;
    }}
    value = {I['load']}(({I['reg']} *)buffer);
    P = {I['or_fn']}(P, {I['slli']}(value, inwordpointer));
    firstpass = 16 - inwordpointer;
    if (bit < firstpass) {{
      inwordpointer += bit;
    }} else {{
      {I['store']}(out++, P);
      P = {I['srli']}(value, firstpass);
      inwordpointer = bit - firstpass;
    }}
  }}
  if (inwordpointer != 0) {{
    {I['store']}(out++, P);
  }}
  return out;
}}

"""


def gen_shortlength_unpack(I):
    lanes = I['lanes']
    return f"""\
const {I['reg']} *simdunpack_shortlength_u16(const {I['reg']} *in, int length,
                                           uint16_t *out, const uint32_t bit) {{
  int k;
  {I['reg']} maskbits;
  int inwordpointer;
  {I['reg']} P;
  if (length == 0)
    return in;
  if (bit == 0) {{
    for (k = 0; k < length; ++k) {{
      out[k] = 0;
    }}
    return in;
  }}
  if (bit == 16) {{
    memcpy(out, in, length * sizeof(uint16_t));
    return (const {I['reg']} *)((uint16_t *)in + length);
  }}
  maskbits = {I['set1']}((1U << bit) - 1);
  inwordpointer = 0;
  P = {I['load']}(({I['reg']} *)in);
  ++in;
  if (length % {lanes} == 0) {{
    for (k = 0; k + 1 < length / {lanes}; ++k) {{
      {I['reg']} answer = {I['srli']}(P, inwordpointer);
      const uint32_t firstpass = 16 - inwordpointer;
      if (bit < firstpass) {{
        inwordpointer += bit;
      }} else {{
        P = {I['load']}(({I['reg']} *)in);
        ++in;
        answer = {I['or_fn']}({I['slli']}(P, firstpass), answer);
        inwordpointer = bit - firstpass;
      }}
      answer = {I['and_fn']}(maskbits, answer);
      {I['store']}(({I['reg']} *)out, answer);
      out += {lanes};
    }}
    if (k < length / {lanes}) {{
      {I['reg']} answer = {I['srli']}(P, inwordpointer);
      const uint32_t firstpass = 16 - inwordpointer;
      if (bit < firstpass) {{
        inwordpointer += bit;
      }} else if (bit == firstpass) {{
        inwordpointer = 0;
      }} else {{
        P = {I['load']}(({I['reg']} *)in);
        ++in;
        answer = {I['or_fn']}({I['slli']}(P, firstpass), answer);
        inwordpointer = bit - firstpass;
      }}
      answer = {I['and_fn']}(maskbits, answer);
      {I['store']}(({I['reg']} *)out, answer);
      out += {lanes};
    }}
  }} else {{
    for (k = 0; k < length / {lanes}; ++k) {{
      {I['reg']} answer = {I['srli']}(P, inwordpointer);
      const uint32_t firstpass = 16 - inwordpointer;
      if (bit < firstpass) {{
        inwordpointer += bit;
      }} else {{
        P = {I['load']}(({I['reg']} *)in);
        ++in;
        answer = {I['or_fn']}({I['slli']}(P, firstpass), answer);
        inwordpointer = bit - firstpass;
      }}
      answer = {I['and_fn']}(maskbits, answer);
      {I['store']}(({I['reg']} *)out, answer);
      out += {lanes};
    }}
    uint16_t buffer[{lanes}];
    {I['reg']} answer = {I['srli']}(P, inwordpointer);
    const uint32_t firstpass = 16 - inwordpointer;
    if (bit < firstpass) {{
      inwordpointer += bit;
    }} else if (bit == firstpass) {{
      inwordpointer = 0;
    }} else {{
      P = {I['load']}(({I['reg']} *)in);
      ++in;
      answer = {I['or_fn']}({I['slli']}(P, firstpass), answer);
      inwordpointer = bit - firstpass;
    }}
    answer = {I['and_fn']}(maskbits, answer);
    {I['store']}(({I['reg']} *)buffer, answer);
    for (k = 0; k < (length % {lanes}); ++k) {{
      *out = buffer[k];
      ++out;
    }}
  }}
  return in;
}}

"""


def gen_utility_functions(I):
    width = I['width']
    lanes = I['lanes']
    block = I['block']

    if width == 128:
        oras_body = f"""\
/* returns the integer logarithm of v (bit width) for uint16 */
static uint32_t bits_u16(const uint16_t v) {{
  return v == 0 ? 0 : 32 - __builtin_clz((uint32_t)v);
}}

static uint32_t oras_u16(const {I['reg']} accumulator) {{
  /* Horizontal OR of {lanes} uint16 lanes into a single uint16 value */
  const {I['reg']} _tmp1 = {I['or_fn']}(
      _mm_srli_si128(accumulator, 8), accumulator);
  const {I['reg']} _tmp2 = {I['or_fn']}(
      _mm_srli_si128(_tmp1, 4), _tmp1);
  const {I['reg']} _tmp3 = {I['or_fn']}(
      _mm_srli_si128(_tmp2, 2), _tmp2);
  return (uint16_t)_mm_extract_epi16(_tmp3, 0);
}}
"""
    else:
        oras_body = f"""\
/* returns the integer logarithm of v (bit width) for uint16 */
static uint32_t bits_u16(const uint16_t v) {{
  return v == 0 ? 0 : 32 - __builtin_clz((uint32_t)v);
}}

static uint32_t oras_u16(const {I['reg']} accumulator) {{
  /* Horizontal OR of {lanes} uint16 lanes into a single uint16 value */
  __m128i lo = _mm256_castsi256_si128(accumulator);
  __m128i hi = _mm256_extracti128_si256(accumulator, 1);
  __m128i combined = _mm_or_si128(lo, hi);
  const __m128i _tmp1 = _mm_or_si128(
      _mm_srli_si128(combined, 8), combined);
  const __m128i _tmp2 = _mm_or_si128(
      _mm_srli_si128(_tmp1, 4), _tmp1);
  const __m128i _tmp3 = _mm_or_si128(
      _mm_srli_si128(_tmp2, 2), _tmp2);
  return (uint16_t)_mm_extract_epi16(_tmp3, 0);
}}
"""

    if width == 128:
        hsum = """\
  /* Horizontal reduction: 4 x int32 -> 1 x int32 */
  __m128i s = sum;
  s = _mm_add_epi32(s, _mm_shuffle_epi32(s, _MM_SHUFFLE(1,0,3,2)));
  s = _mm_add_epi32(s, _mm_shuffle_epi32(s, _MM_SHUFFLE(2,3,0,1)));

  uint32_t finalsum = (uint32_t)_mm_cvtsi128_si32(s);"""
    else:
        hsum = """\
  /* 256-bit horizontal reduction */
  __m128i lo = _mm256_castsi256_si128(sum);
  __m128i hi = _mm256_extracti128_si256(sum, 1);
  __m128i s = _mm_add_epi32(lo, hi);
  s = _mm_add_epi32(s, _mm_shuffle_epi32(s, _MM_SHUFFLE(1,0,3,2)));
  s = _mm_add_epi32(s, _mm_shuffle_epi32(s, _MM_SHUFFLE(2,3,0,1)));

  uint32_t finalsum = (uint32_t)_mm_cvtsi128_si32(s);"""

    return f"""\
{oras_body}

uint32_t maxbits_length_u16(const uint16_t *in, size_t length) {{
  size_t k;
  size_t lengthdividedby{lanes} = length / {lanes};
  size_t offset = lengthdividedby{lanes} * {lanes};
  uint32_t bigxor = 0;
  if (lengthdividedby{lanes} > 0) {{
    const {I['reg']} *pin = (const {I['reg']} *)(in);
    {I['reg']} accumulator = {I['load']}(pin);
    k = 1;
    for (; {lanes} * k < {lanes} * lengthdividedby{lanes}; ++k) {{
      {I['reg']} newvec = {I['load']}(pin + k);
      accumulator = {I['or_fn']}(accumulator, newvec);
    }}
    bigxor = oras_u16(accumulator);
  }}
  for (k = offset; k < length; ++k)
    bigxor |= in[k];
  return bits_u16((uint16_t)bigxor);
}}

int simdpack_compressedbytes_u16(int length, const uint32_t bit) {{
  if (bit == 0)
    return 0;
  if (bit == 16) {{
    return length * sizeof(uint16_t);
  }}
  /* Each group of {lanes} uint16 lanes packs to ({lanes} * bit) bits = bit bytes per group.
     Total groups = (length + {lanes - 1}) / {lanes}.  Round up to {I['reg']} boundary. */
  return (((length + {lanes - 1}) / {lanes}) * bit + 15) / 16 * sizeof({I['reg']});
}}

{I['reg']} *simdpack_length_u16(const uint16_t *in, size_t length, {I['reg']} *out,
                              const uint32_t bit) {{
  size_t k;
  for (k = 0; k < length / SIMDBlockSize_u16; ++k) {{
    simdpack_u16(in, out, bit);
    in += SIMDBlockSize_u16;
    out += bit;
  }}
  return simdpack_shortlength_u16(in, length % SIMDBlockSize_u16, out, bit);
}}

const {I['reg']} *simdunpack_length_u16(const {I['reg']} *in, size_t length,
                                      uint16_t *out, const uint32_t bit,
                                      uint32_t *outsum) {{
  {I['reg']} sum = {I['setzero']}();
  size_t k;
  for (k = 0; k < length / SIMDBlockSize_u16; ++k) {{
    simdunpack_u16(in, out, bit, &sum);
    out += SIMDBlockSize_u16;
    in += bit;
  }}
{hsum}

  /* Handle remainder with scalar sum */
  size_t remainder = length % SIMDBlockSize_u16;
  if (remainder > 0) {{
    in = simdunpack_shortlength_u16(in, remainder, out, bit);
    size_t i;
    for (i = 0; i < remainder; ++i) {{
      finalsum += out[i];
    }}
  }}
  *outsum = finalsum;
  return in;
}}

"""


def main():
    parser = argparse.ArgumentParser(
        description='Generate SIMD bit-packing for uint16')
    parser.add_argument('--width', type=int, choices=[128, 256], default=128,
                        help='Register width in bits (128=AVX, 256=AVX2)')
    args = parser.parse_args()

    I = intrinsics(args.width)
    lanes = args.width // LANE_BITS
    block = lanes * MAX_BIT  # 128 for 128-bit, 256 for 256-bit
    I['lanes'] = lanes
    I['block'] = block
    I['width'] = args.width

    out = []
    out.append(gen_header(I))
    out.append(gen_null_unpacker(I))

    # Pack functions for all bit widths
    for bit in range(MAX_BIT + 1):
        out.append(gen_pack_function(bit, I))

    out.append(gen_pack_dispatcher(I))

    # Unpack+sum functions for all bit widths
    for bit in range(1, MAX_BIT + 1):
        out.append(gen_unpack_function(bit, I))

    out.append(gen_unpack_dispatcher(I))

    # Short-length handlers
    out.append(gen_shortlength_pack(I))
    out.append(gen_shortlength_unpack(I))

    # Utility functions
    out.append(gen_utility_functions(I))

    script_dir = os.path.dirname(os.path.abspath(__file__))
    src_dir = os.path.join(script_dir, '..', 'src')
    out_path = os.path.join(src_dir, 'simdbitpacking_u16.c')

    with open(out_path, 'w') as f:
        f.write("".join(out))
    print(f"Generated {out_path}")


if __name__ == "__main__":
    main()
