#!/usr/bin/env python3
"""
Generate simdbitpacking.c — SIMD bit-packing/unpacking for uint32,
with fused sum aggregation (no output writes during unpack).

Supports 128-bit (AVX) and 256-bit (AVX2) register widths.

Usage:
  python gen_simdbitpacking.py --width 128   # AVX (128-bit registers)
  python gen_simdbitpacking.py --width 256   # AVX2 (256-bit registers)
"""
import argparse
import os
import sys

LANE_BITS = 32
MAX_BIT = 32


def intrinsics(width):
    """Return a dict of intrinsic names for the given register width."""
    if width == 128:
        return dict(
            reg='__m128i',
            load='_mm_loadu_si128',
            store='_mm_storeu_si128',
            setzero='_mm_setzero_si128',
            or_fn='_mm_or_si128',
            and_fn='_mm_and_si128',
            slli='_mm_slli_epi32',
            srli='_mm_srli_epi32',
            set1='_mm_set1_epi32',
            add='_mm_add_epi32',
            shuffle='_mm_shuffle_epi32',
            cvt='_mm_cvtsi128_si32',
            srli_bytes='_mm_srli_si128',
            extract16='_mm_extract_epi16',
        )
    else:
        return dict(
            reg='__m256i',
            load='_mm256_loadu_si256',
            store='_mm256_storeu_si256',
            setzero='_mm256_setzero_si256',
            or_fn='_mm256_or_si256',
            and_fn='_mm256_and_si256',
            slli='_mm256_slli_epi32',
            srli='_mm256_srli_epi32',
            set1='_mm256_set1_epi32',
            add='_mm256_add_epi32',
            shuffle='_mm_shuffle_epi32',       # used in hsum only (128-bit)
            cvt='_mm_cvtsi128_si32',            # used in hsum only (128-bit)
            cast256to128='_mm256_castsi256_si128',
            extracti128='_mm256_extracti128_si256',
        )


def gen_header(I):
    lines = []
    lines.append(f"""\
/**
 * Auto-generated uint32 SIMD bit-packing with fused sum aggregation.
 * Generated by gen_simdbitpacking.py (width={I['width']})
 *
 * This code is released under a BSD License.
 */
#include "simdbitpacking.h"
#include <string.h>
""")

    block = I['block']
    lanes = I['lanes']

    lines.append(f"#define SIMDBlockSize {block}")
    lines.append("")

    # aggregate_sums: just epi32 add to sum_lo (sum_hi unused, kept for API compat)
    lines.append(f"static void aggregate_sums({I['reg']} OutReg, {I['reg']}* sum_lo, {I['reg']}* sum_hi) {{")
    lines.append(f"    *sum_lo = {I['add']}(*sum_lo, OutReg);")
    lines.append("}")
    lines.append("")

    # Null unpacker
    lines.append(f"static void SIMD_nullunpacker32(const {I['reg']} *_in, uint32_t *out) {{")
    lines.append("  (void)_in;")
    lines.append(f"  memset(out, 0, {block} * sizeof(uint32_t));")
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def gen_pack_without_mask_function(bit, I):
    """Generate pack-without-mask function for given bit width."""
    lines = []
    lanes = I['lanes']
    block = I['block']
    total_inputs = block // lanes  # always 32 for uint32

    if bit == 0:
        lines.append(f"static void __SIMD_fastpackwithoutmask0_32("
                     f"const uint32_t *_in, {I['reg']} *out) {{")
        lines.append("  (void)out;")
        lines.append("  (void)_in;")
        lines.append("}")
        lines.append("")
        return "\n".join(lines)

    lines.append(f"static void __SIMD_fastpackwithoutmask{bit}_32("
                 f"const uint32_t *_in, {I['reg']} *out) {{")
    lines.append(f"  const {I['reg']} *in = (const {I['reg']} *)(_in);")
    lines.append(f"  {I['reg']} OutReg;")
    lines.append(f"  {I['reg']} InReg = {I['load']}(in);")
    lines.append("")

    if bit == LANE_BITS:
        # bit=32: just copy
        lines.append("  OutReg = InReg;")
        lines.append(f"  {I['store']}(out, OutReg);")
        lines.append("  ++out;")
        for i in range(1, total_inputs):
            lines.append(f"  InReg = {I['load']}(++in);")
            lines.append("")
            lines.append("  OutReg = InReg;")
            lines.append(f"  {I['store']}(out, OutReg);")
            lines.append("  ++out;")
        lines.append("}")
        lines.append("")
        return "\n".join(lines)

    # General case
    bit_pos = 0
    out_word = 0

    lines.append("  OutReg = InReg;")
    bit_pos = bit

    for i in range(1, total_inputs):
        lines.append(f"  InReg = {I['load']}(++in);")
        lines.append("")

        remaining = LANE_BITS - bit_pos

        if remaining >= bit:
            if bit_pos == 0:
                lines.append("  OutReg = InReg;")
            else:
                lines.append(f"  OutReg = {I['or_fn']}(OutReg, {I['slli']}(InReg, {bit_pos}));")
            bit_pos += bit
        else:
            if remaining > 0:
                lines.append(f"  OutReg = {I['or_fn']}(OutReg, {I['slli']}(InReg, {bit_pos}));")
            lines.append(f"  {I['store']}(out, OutReg);")
            lines.append("  ++out;")
            if remaining > 0:
                lines.append(f"  OutReg = {I['srli']}(InReg, {bit} - {bit - remaining});")
            else:
                lines.append("  OutReg = InReg;")
            bit_pos = bit - remaining

        if bit_pos == LANE_BITS:
            lines.append(f"  {I['store']}(out, OutReg);")
            lines.append("  ++out;")
            bit_pos = 0

    if bit_pos > 0:
        lines.append(f"  {I['store']}(out, OutReg);")

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def gen_pack_with_mask_function(bit, I):
    """Generate pack-with-mask function for given bit width."""
    lines = []
    lanes = I['lanes']
    block = I['block']
    total_inputs = block // lanes

    if bit == 0:
        lines.append(f"static void __SIMD_fastpack0_32("
                     f"const uint32_t *_in, {I['reg']} *out) {{")
        lines.append("  (void)out;")
        lines.append("  (void)_in;")
        lines.append("}")
        lines.append("")
        return "\n".join(lines)

    lines.append(f"static void __SIMD_fastpack{bit}_32("
                 f"const uint32_t *_in, {I['reg']} *out) {{")
    lines.append(f"  const {I['reg']} *in = (const {I['reg']} *)(_in);")
    lines.append(f"  {I['reg']} OutReg;")
    lines.append("")

    if bit == LANE_BITS:
        # No mask needed for full-width
        lines.append(f"  {I['reg']} InReg = {I['load']}(in);")
        lines.append("  OutReg = InReg;")
        lines.append(f"  {I['store']}(out, OutReg);")
        lines.append("  ++out;")
        for i in range(1, total_inputs):
            lines.append(f"  InReg = {I['load']}(++in);")
            lines.append("")
            lines.append("  OutReg = InReg;")
            lines.append(f"  {I['store']}(out, OutReg);")
            lines.append("  ++out;")
        lines.append("}")
        lines.append("")
        return "\n".join(lines)

    lines.append(f"  const {I['reg']} mask = {I['set1']}((1U << {bit}) - 1);")
    lines.append("")
    lines.append(f"  {I['reg']} InReg = {I['and_fn']}({I['load']}(in), mask);")
    lines.append("  OutReg = InReg;")

    bit_pos = bit

    for i in range(1, total_inputs):
        lines.append(f"  InReg = {I['and_fn']}({I['load']}(++in), mask);")
        lines.append("")

        remaining = LANE_BITS - bit_pos

        if remaining >= bit:
            if bit_pos == 0:
                lines.append("  OutReg = InReg;")
            else:
                lines.append(f"  OutReg = {I['or_fn']}(OutReg, {I['slli']}(InReg, {bit_pos}));")
            bit_pos += bit
        else:
            if remaining > 0:
                lines.append(f"  OutReg = {I['or_fn']}(OutReg, {I['slli']}(InReg, {bit_pos}));")
            lines.append(f"  {I['store']}(out, OutReg);")
            lines.append("  ++out;")
            if remaining > 0:
                lines.append(f"  OutReg = {I['srli']}(InReg, {bit} - {bit - remaining});")
            else:
                lines.append("  OutReg = InReg;")
            bit_pos = bit - remaining

        if bit_pos == LANE_BITS:
            lines.append(f"  {I['store']}(out, OutReg);")
            lines.append("  ++out;")
            bit_pos = 0

    if bit_pos > 0:
        lines.append(f"  {I['store']}(out, OutReg);")

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def gen_unpack_function(bit, I):
    """Generate fused unpack+sum function for given bit width."""
    lines = []
    lanes = I['lanes']
    block = I['block']
    total_values = block // lanes  # 32 for uint32

    if bit == 0:
        return ""

    lines.append(f"static void __SIMD_fastunpack{bit}_32("
                 f"const {I['reg']} *in, uint32_t *_out, "
                 f"{I['reg']}* sum_lo, {I['reg']}* sum_hi) {{")
    lines.append("")

    if bit == LANE_BITS:
        # bit=32: each input word IS the values
        lines.append(f"  /* {I['reg']} *out = ({I['reg']} *)(_out); */")
        lines.append("  uint32_t outer;")
        lines.append("")
        lines.append(f"  for (outer = 0; outer < {total_values}; ++outer) {{")
        lines.append(f"    /* {I['store']}(out++, {I['load']}(in++)); */")
        lines.append(f"    aggregate_sums({I['load']}(in++), sum_lo, sum_hi);")
        lines.append("  }")
        lines.append("}")
        lines.append("")
        return "\n".join(lines)

    lines.append(f"  /* {I['reg']} *out = ({I['reg']} *)(_out); */")
    lines.append(f"  {I['reg']} InReg = {I['load']}(in);")
    lines.append(f"  {I['reg']} OutReg;")
    lines.append(f"  const {I['reg']} mask = {I['set1']}((1U << {bit}) - 1);")
    lines.append("")

    bit_pos = 0

    for v in range(total_values):
        remaining = LANE_BITS - bit_pos

        if remaining >= bit:
            if bit_pos == 0:
                lines.append(f"  OutReg = {I['and_fn']}(InReg, mask);")
            else:
                lines.append(f"  OutReg = {I['and_fn']}({I['srli']}(InReg, {bit_pos}), mask);")
            lines.append(f"  /* {I['store']}(out++, OutReg); */")
            lines.append("    aggregate_sums(OutReg, sum_lo, sum_hi);")
            lines.append("")
            bit_pos += bit
        else:
            if remaining > 0:
                lines.append(f"  OutReg = {I['srli']}(InReg, {bit_pos});")
            lines.append(f"  InReg = {I['load']}(++in);")
            lines.append("")
            need = bit - remaining
            if remaining > 0:
                lines.append("  OutReg =")
                lines.append(f"      {I['or_fn']}(OutReg, {I['and_fn']}({I['slli']}(InReg, {bit} - {need}), mask));")
            else:
                lines.append(f"  OutReg = {I['and_fn']}(InReg, mask);")
            lines.append(f"  /* {I['store']}(out++, OutReg); */")
            lines.append("    aggregate_sums(OutReg, sum_lo, sum_hi);")
            lines.append("")
            bit_pos = need

        if bit_pos == LANE_BITS:
            if v < total_values - 1:
                lines.append(f"  InReg = {I['load']}(++in);")
            bit_pos = 0

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def gen_dispatchers(I):
    lines = []

    # Unpack dispatcher
    lines.append(f"void simdunpack(const {I['reg']} *in, uint32_t *out, "
                 f"const uint32_t bit, {I['reg']}* sum_lo, {I['reg']}* sum_hi) {{")
    lines.append("  switch (bit) {")
    lines.append("  case 0:")
    lines.append("    SIMD_nullunpacker32(in, out);")
    lines.append("    break;")
    lines.append("")
    for b in range(1, MAX_BIT + 1):
        lines.append(f"  case {b}:")
        lines.append(f"    __SIMD_fastunpack{b}_32(in, out, sum_lo, sum_hi);")
        lines.append("    break;")
        lines.append("")
    lines.append("  default:")
    lines.append("    break;")
    lines.append("  }")
    lines.append("")
    lines.append("  return;")
    lines.append("}")
    lines.append("")

    # Pack-without-mask dispatcher
    lines.append("/*assumes that integers fit in the prescribed number of bits*/")
    lines.append(f"void simdpackwithoutmask(const uint32_t *in, {I['reg']} *out, "
                 f"const uint32_t bit) {{")
    lines.append("  switch (bit) {")
    lines.append("  case 0:")
    lines.append("    return;")
    lines.append("")
    for b in range(1, MAX_BIT + 1):
        lines.append(f"  case {b}:")
        lines.append(f"    __SIMD_fastpackwithoutmask{b}_32(in, out);")
        lines.append("    return;")
        lines.append("")
    lines.append("  default:")
    lines.append("    break;")
    lines.append("  }")
    lines.append("}")
    lines.append("")

    # Pack-with-mask dispatcher
    lines.append(f"void simdpack(const uint32_t *in, {I['reg']} *out, "
                 f"const uint32_t bit) {{")
    lines.append("  switch (bit) {")
    lines.append("  case 0:")
    lines.append("    return;")
    lines.append("")
    for b in range(1, MAX_BIT + 1):
        lines.append(f"  case {b}:")
        lines.append(f"    __SIMD_fastpack{b}_32(in, out);")
        lines.append("    return;")
        lines.append("")
    lines.append("  default:")
    lines.append("    break;")
    lines.append("  }")
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def gen_utility_functions(I):
    """Generate shortlength pack/unpack, simdfastset, compressedbytes, etc."""
    lines = []
    block = I['block']
    lanes = I['lanes']
    width = I['width']

    # simdpack_shortlength
    lines.append(f"{I['reg']} *simdpack_shortlength(const uint32_t *in, int length, "
                 f"{I['reg']} *out,")
    lines.append(f"                              const uint32_t bit) {{")
    lines.append("  int k;")
    lines.append("  int inwordpointer;")
    lines.append(f"  {I['reg']} P;")
    lines.append("  uint32_t firstpass;")
    lines.append("  if (bit == 0)")
    lines.append("    return out; /* nothing to do */")
    lines.append("  if (bit == 32) {")
    lines.append("    memcpy(out, in, length * sizeof(uint32_t));")
    lines.append(f"    return ({I['reg']} *)((uint32_t *)out + length);")
    lines.append("  }")
    lines.append("  inwordpointer = 0;")
    lines.append(f"  P = {I['setzero']}();")
    lines.append(f"  for (k = 0; k < length / {lanes}; ++k) {{")
    lines.append(f"    {I['reg']} value = {I['load']}(((const {I['reg']} *)in + k));")
    lines.append(f"    P = {I['or_fn']}(P, {I['slli']}(value, inwordpointer));")
    lines.append("    firstpass = sizeof(uint32_t) * 8 - inwordpointer;")
    lines.append("    if (bit < firstpass) {")
    lines.append("      inwordpointer += bit;")
    lines.append("    } else {")
    lines.append(f"      {I['store']}(out++, P);")
    lines.append(f"      P = {I['srli']}(value, firstpass);")
    lines.append("      inwordpointer = bit - firstpass;")
    lines.append("    }")
    lines.append("  }")
    lines.append(f"  if (length % {lanes} != 0) {{")
    lines.append(f"    uint32_t buffer[{lanes}];")
    lines.append(f"    {I['reg']} value;")
    lines.append(f"    for (k = 0; k < (length % {lanes}); ++k) {{")
    lines.append(f"      buffer[k] = in[length / {lanes} * {lanes} + k];")
    lines.append("    }")
    lines.append(f"    for (k = (length % {lanes}); k < {lanes}; ++k) {{")
    lines.append("      buffer[k] = 0;")
    lines.append("    }")
    lines.append(f"    value = {I['load']}(({I['reg']} *)buffer);")
    lines.append(f"    P = {I['or_fn']}(P, {I['slli']}(value, inwordpointer));")
    lines.append("    firstpass = sizeof(uint32_t) * 8 - inwordpointer;")
    lines.append("    if (bit < firstpass) {")
    lines.append("      inwordpointer += bit;")
    lines.append("    } else {")
    lines.append(f"      {I['store']}(out++, P);")
    lines.append(f"      P = {I['srli']}(value, firstpass);")
    lines.append("      inwordpointer = bit - firstpass;")
    lines.append("    }")
    lines.append("  }")
    lines.append("  if (inwordpointer != 0) {")
    lines.append(f"    {I['store']}(out++, P);")
    lines.append("  }")
    lines.append("  return out;")
    lines.append("}")
    lines.append("")

    # simdunpack_shortlength
    lines.append(f"const {I['reg']} *simdunpack_shortlength(const {I['reg']} *in, int length,")
    lines.append(f"                                      uint32_t *out, const uint32_t bit) {{")
    lines.append("  int k;")
    lines.append(f"  {I['reg']} maskbits;")
    lines.append("  int inwordpointer;")
    lines.append(f"  {I['reg']} P;")
    lines.append("  if (length == 0)")
    lines.append("    return in;")
    lines.append("  if (bit == 0) {")
    lines.append("    for (k = 0; k < length; ++k) {")
    lines.append("      out[k] = 0;")
    lines.append("    }")
    lines.append("    return in;")
    lines.append("  }")
    lines.append("  if (bit == 32) {")
    lines.append("    memcpy(out, in, length * sizeof(uint32_t));")
    lines.append(f"    return (const {I['reg']} *)((uint32_t *)in + length);")
    lines.append("  }")
    lines.append(f"  maskbits = {I['set1']}((1U << bit) - 1);")
    lines.append("  inwordpointer = 0;")
    lines.append(f"  P = {I['load']}(({I['reg']} *)in);")
    lines.append("  ++in;")
    lines.append(f"  if (length % {lanes} == 0) {{")
    lines.append("")
    lines.append(f"    for (k = 0; k + 1 < length / {lanes}; ++k) {{")
    lines.append(f"      {I['reg']} answer = {I['srli']}(P, inwordpointer);")
    lines.append("      const uint32_t firstpass = sizeof(uint32_t) * 8 - inwordpointer;")
    lines.append("      if (bit < firstpass) {")
    lines.append("        inwordpointer += bit;")
    lines.append("      } else {")
    lines.append(f"        P = {I['load']}(({I['reg']} *)in);")
    lines.append("        ++in;")
    lines.append(f"        answer = {I['or_fn']}({I['slli']}(P, firstpass), answer);")
    lines.append("        inwordpointer = bit - firstpass;")
    lines.append("      }")
    lines.append(f"      answer = {I['and_fn']}(maskbits, answer);")
    lines.append(f"      {I['store']}(({I['reg']} *)out, answer);")
    lines.append(f"      out += {lanes};")
    lines.append("    }")
    lines.append(f"    if (k < length / {lanes}) {{")
    lines.append(f"      {I['reg']} answer = {I['srli']}(P, inwordpointer);")
    lines.append("      const uint32_t firstpass = sizeof(uint32_t) * 8 - inwordpointer;")
    lines.append("      if (bit < firstpass) {")
    lines.append("        inwordpointer += bit;")
    lines.append("      } else if (bit == firstpass) {")
    lines.append("        inwordpointer = 0;")
    lines.append("      } else {")
    lines.append(f"        P = {I['load']}(({I['reg']} *)in);")
    lines.append("        ++in;")
    lines.append(f"        answer = {I['or_fn']}({I['slli']}(P, firstpass), answer);")
    lines.append("        inwordpointer = bit - firstpass;")
    lines.append("      }")
    lines.append(f"      answer = {I['and_fn']}(maskbits, answer);")
    lines.append(f"      {I['store']}(({I['reg']} *)out, answer);")
    lines.append(f"      out += {lanes};")
    lines.append("    }")
    lines.append("")
    lines.append("  } else {")
    lines.append(f"    for (k = 0; k < length / {lanes}; ++k) {{")
    lines.append(f"      {I['reg']} answer = {I['srli']}(P, inwordpointer);")
    lines.append("      const uint32_t firstpass = sizeof(uint32_t) * 8 - inwordpointer;")
    lines.append("      if (bit < firstpass) {")
    lines.append("        inwordpointer += bit;")
    lines.append("      } else {")
    lines.append(f"        P = {I['load']}(({I['reg']} *)in);")
    lines.append("        ++in;")
    lines.append(f"        answer = {I['or_fn']}({I['slli']}(P, firstpass), answer);")
    lines.append("        inwordpointer = bit - firstpass;")
    lines.append("      }")
    lines.append(f"      answer = {I['and_fn']}(maskbits, answer);")
    lines.append(f"      {I['store']}(({I['reg']} *)out, answer);")
    lines.append(f"      out += {lanes};")
    lines.append("    }")
    lines.append(f"    uint32_t buffer[{lanes}];")
    lines.append(f"    {I['reg']} answer = {I['srli']}(P, inwordpointer);")
    lines.append("    const uint32_t firstpass = sizeof(uint32_t) * 8 - inwordpointer;")
    lines.append("    if (bit < firstpass) {")
    lines.append("      inwordpointer += bit;")
    lines.append("    } else if (bit == firstpass) {")
    lines.append("      inwordpointer = 0;")
    lines.append("    } else {")
    lines.append(f"      P = {I['load']}(({I['reg']} *)in);")
    lines.append("      ++in;")
    lines.append(f"      answer = {I['or_fn']}({I['slli']}(P, firstpass), answer);")
    lines.append("      inwordpointer = bit - firstpass;")
    lines.append("    }")
    lines.append(f"    answer = {I['and_fn']}(maskbits, answer);")
    lines.append(f"    {I['store']}(({I['reg']} *)buffer, answer);")
    lines.append(f"    for (k = 0; k < (length % {lanes}); ++k) {{")
    lines.append("      *out = buffer[k];")
    lines.append("      ++out;")
    lines.append("    }")
    lines.append("  }")
    lines.append("  return in;")
    lines.append("}")
    lines.append("")

    # simdfastset
    lines.append(f"void simdfastset({I['reg']} *in128, uint32_t b, uint32_t value, size_t index) {{")
    lines.append("  uint32_t *in = (uint32_t *)in128;")
    lines.append(f"  const int lane = index % {lanes};             /* we have {lanes} interleaved lanes */")
    lines.append(f"  const int bitsinlane = (index / {lanes}) * b; /* how many bits in lane */")
    lines.append("  const int firstwordinlane = bitsinlane / 32;")
    lines.append("  const int secondwordinlane = (bitsinlane + b - 1) / 32;")
    lines.append("  const uint32_t mask = (1U << b) - 1;")
    lines.append("  if (b == 0)")
    lines.append("    return;")
    lines.append("  /* we zero */")
    lines.append("  if (b == 32)")
    lines.append(f"    in[{lanes} * firstwordinlane + lane] = 0;")
    lines.append("  else")
    lines.append(f"    in[{lanes} * firstwordinlane + lane] &= ~(mask << (bitsinlane % 32));")
    lines.append("")
    lines.append("  /* we write */")
    lines.append(f"  in[{lanes} * firstwordinlane + lane] |= (value << (bitsinlane % 32));")
    lines.append("")
    lines.append("  if (firstwordinlane == secondwordinlane) {")
    lines.append("    /* easy common case*/")
    lines.append("    return;")
    lines.append("  } else {")
    lines.append("    /* harder case where we need to combine two words */")
    lines.append("    const int firstbits = 32 - (bitsinlane % 32);")
    lines.append("    const int usablebits = b - firstbits;")
    lines.append("    const uint32_t mask2 = (1U << usablebits) - 1;")
    lines.append(f"    in[{lanes} * firstwordinlane + {lanes} + lane] &= ~mask2;             /* we zero */")
    lines.append(f"    in[{lanes} * firstwordinlane + {lanes} + lane] |= value >> firstbits; /* we write */")
    lines.append("    return;")
    lines.append("  }")
    lines.append("}")
    lines.append("")

    # simdpack_compressedbytes
    lines.append("int simdpack_compressedbytes(int length, const uint32_t bit) {")
    lines.append("  if (bit == 0)")
    lines.append("    return 0; /* nothing to do */")
    lines.append("  if (bit == 32) {")
    lines.append("    return length * sizeof(uint32_t);")
    lines.append("  }")
    lines.append(f"  return (((length + {lanes - 1}) / {lanes}) * bit + 31) / 32 * sizeof({I['reg']});")
    lines.append("}")
    lines.append("")

    # simdpack_length
    lines.append(f"{I['reg']} *simdpack_length(const uint32_t *in, size_t length, {I['reg']} *out,")
    lines.append("                         const uint32_t bit) {")
    lines.append("  size_t k;")
    lines.append("  for (k = 0; k < length / SIMDBlockSize; ++k) {")
    lines.append("    simdpack(in, out, bit);")
    lines.append("    in += SIMDBlockSize;")
    lines.append("    out += bit;")
    lines.append("  }")
    lines.append("  return simdpack_shortlength(in, length % SIMDBlockSize, out, bit);")
    lines.append("}")
    lines.append("")

    # simdunpack_length with horizontal sum
    lines.append(f"const {I['reg']} *simdunpack_length(const {I['reg']} *in, size_t length,")
    lines.append("                                 uint32_t *out, const uint32_t bit, uint64_t* outsum) {")
    lines.append(f"  {I['reg']} sum_lo = {I['setzero']}();")
    lines.append(f"  {I['reg']} sum_hi = {I['setzero']}();")
    lines.append("  size_t k;")
    lines.append("  for (k = 0; k < length / SIMDBlockSize; ++k) {")
    lines.append("    simdunpack(in, out, bit, &sum_lo, &sum_hi);")
    lines.append("    out += SIMDBlockSize;")
    lines.append("    in += bit;")
    lines.append("  }")

    # Horizontal reduction
    if width == 128:
        lines.append("  __m128i s = sum_lo;")
        lines.append("")
        lines.append("  s = _mm_add_epi32(s, _mm_shuffle_epi32(s, _MM_SHUFFLE(1,0,3,2)));")
        lines.append("  s = _mm_add_epi32(s, _mm_shuffle_epi32(s, _MM_SHUFFLE(2,3,0,1)));")
        lines.append("")
        lines.append("  uint64_t sum = (uint32_t)_mm_cvtsi128_si32(s);")
    else:
        lines.append("  /* 256-bit horizontal sum */")
        lines.append("  __m128i lo = _mm256_castsi256_si128(sum_lo);")
        lines.append("  __m128i hi = _mm256_extracti128_si256(sum_lo, 1);")
        lines.append("  __m128i s = _mm_add_epi32(lo, hi);")
        lines.append("  s = _mm_add_epi32(s, _mm_shuffle_epi32(s, _MM_SHUFFLE(1,0,3,2)));")
        lines.append("  s = _mm_add_epi32(s, _mm_shuffle_epi32(s, _MM_SHUFFLE(2,3,0,1)));")
        lines.append("")
        lines.append("  uint64_t sum = (uint32_t)_mm_cvtsi128_si32(s);")

    lines.append("  size_t remainder = length % SIMDBlockSize;")
    lines.append("  if (remainder > 0) {")
    lines.append("      in = simdunpack_shortlength(in, remainder, out, bit);")
    lines.append("      size_t i;")
    lines.append("      for (i = 0; i < remainder; ++i) {")
    lines.append("          sum += out[i];")
    lines.append("      }")
    lines.append("  }")
    lines.append("  *outsum = sum;")
    lines.append("  return in;")
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description='Generate SIMD bit-packing for uint32')
    parser.add_argument('--width', type=int, choices=[128, 256], default=128,
                        help='Register width in bits (128=AVX, 256=AVX2)')
    args = parser.parse_args()

    I = intrinsics(args.width)
    lanes = args.width // LANE_BITS
    block = lanes * MAX_BIT  # 128 for 128-bit, 256 for 256-bit
    I['lanes'] = lanes
    I['block'] = block
    I['width'] = args.width

    out = []
    out.append(gen_header(I))

    # Pack-without-mask functions
    for bit in range(MAX_BIT + 1):
        out.append(gen_pack_without_mask_function(bit, I))

    # Pack-with-mask functions
    for bit in range(MAX_BIT + 1):
        out.append(gen_pack_with_mask_function(bit, I))

    # Unpack functions
    for bit in range(1, MAX_BIT + 1):
        out.append(gen_unpack_function(bit, I))

    # Dispatchers
    out.append(gen_dispatchers(I))

    # Utility functions
    out.append(gen_utility_functions(I))

    script_dir = os.path.dirname(os.path.abspath(__file__))
    src_dir = os.path.join(script_dir, '..', 'src')
    out_path = os.path.join(src_dir, 'simdbitpacking.c')

    with open(out_path, 'w') as f:
        f.write("\n".join(out))
    print(f"Generated {out_path}")


if __name__ == "__main__":
    main()
