#!/usr/bin/env python3
"""
Generate simdbitpacking_u16.c — SIMD bit-packing/unpacking for uint16,
with fused sum aggregation (no output writes during unpack).

Mirrors simdbitpacking.c but for 16-bit lanes:
  - _mm_*_epi32 → _mm_*_epi16
  - 4 values per __m128i → 8 values per __m128i
  - bit widths 0..16 instead of 0..32
  - aggregate_sums_u16: _mm_madd_epi16 + _mm_add_epi32 (widens to int32)
  - SIMDBlockSize = 128 values (same as 32-bit)
"""

BLOCK = 128        # SIMDBlockSize — values per block
LANES = 8          # uint16 values per __m128i
LANE_BITS = 16     # bits per lane
MAX_BIT = 16       # maximum bit width


def vals_per_word(bit):
    """How many complete values fit in one SIMD lane."""
    return LANE_BITS // bit if bit > 0 else 0


def gen_header():
    return """\
/**
 * Auto-generated uint16 SIMD bit-packing with fused sum aggregation.
 * Generated by gen_simdbitpacking_u16.py
 *
 * This code is released under a BSD License.
 */
#include "simdbitpacking_u16.h"
#include <string.h>

#define SIMDBlockSize_u16 128

static const __m128i ones_u16 = {0x0001000100010001ULL, 0x0001000100010001ULL};

static void aggregate_sums_u16(__m128i OutReg, __m128i* sum) {
    /* Widen 8 x uint16 -> 4 x int32 via pairwise multiply-add, then accumulate.
       Correct when all uint16 values <= 32767 (i.e. data fits signed int16).
       2 instructions / 8 values = 0.25 inst/val. */
    *sum = _mm_add_epi32(*sum, _mm_madd_epi16(OutReg, ones_u16));
}

"""


def gen_null_unpacker():
    return """\
static void SIMD_nullunpacker16(const __m128i *_in, uint16_t *out) {
  (void)_in;
  memset(out, 0, %d * sizeof(uint16_t));
}

""" % BLOCK


def gen_null_packer():
    return """\
static void __SIMD_fastpackwithoutmask0_16(const uint16_t *_in, __m128i *out) {
  (void)out;
  (void)_in;
}

"""


def gen_pack_function(bit):
    """Generate pack function for given bit width.

    Packs BLOCK (128) uint16 values at `bit` bits each into `bit` __m128i words.
    Each __m128i has 8 interleaved lanes of 16 bits.
    Input: BLOCK/8 = 16 __m128i registers of uint16 values.
    """
    if bit == 0:
        return gen_null_packer()

    lines = []
    lines.append("static void __SIMD_fastpackwithoutmask%d_16(const uint16_t *_in, __m128i *out) {" % bit)
    lines.append("  const __m128i *in = (const __m128i *)(_in);")
    lines.append("  __m128i OutReg;")
    lines.append("  __m128i InReg = _mm_loadu_si128(in);")
    lines.append("")

    if bit == LANE_BITS:
        # bit=16: just copy all 16 input __m128i to output
        lines.pop()  # remove "  __m128i OutReg;"
        lines.append("  _mm_storeu_si128(out, InReg);")
        for i in range(1, BLOCK // LANES):
            lines.append("  InReg = _mm_loadu_si128(++in);")
            lines.append("  _mm_storeu_si128(out + %d, InReg);" % i)
        lines.append("}")
        lines.append("")
        return "\n".join(lines)

    # General case: interleave values into output words
    # Track bit position within each output word (per lane)
    out_word = 0       # which output __m128i we're building
    in_pos = 0         # which input __m128i we've loaded (0-based)
    bit_pos = 0        # bit offset within current output word's lane

    lines.append("  OutReg = InReg;")
    in_pos = 0
    bit_pos = bit

    total_inputs = BLOCK // LANES  # 16

    for i in range(1, total_inputs):
        lines.append("  InReg = _mm_loadu_si128(++in);")
        in_pos += 1

        remaining = LANE_BITS - bit_pos  # bits remaining in current output word

        if remaining >= bit:
            # Value fits entirely in current output word
            if bit_pos == 0:
                lines.append("  OutReg = InReg;")
            else:
                lines.append("  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, %d));" % bit_pos)
            bit_pos += bit
        else:
            # Value spans two output words
            if remaining > 0:
                lines.append("  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, %d));" % bit_pos)
            lines.append("  _mm_storeu_si128(out + %d, OutReg);" % out_word)
            out_word += 1
            if remaining > 0:
                lines.append("  OutReg = _mm_srli_epi16(InReg, %d);" % remaining)
            else:
                lines.append("  OutReg = InReg;")
            bit_pos = bit - remaining

        if bit_pos == LANE_BITS:
            lines.append("  _mm_storeu_si128(out + %d, OutReg);" % out_word)
            out_word += 1
            bit_pos = 0

    # Flush last output word if needed
    if bit_pos > 0:
        lines.append("  _mm_storeu_si128(out + %d, OutReg);" % out_word)

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def gen_unpack_function(bit):
    """Generate fused unpack+sum function for given bit width.

    Unpacks BLOCK (128) uint16 values and aggregates sum.
    No output writes — fused mode only.
    """
    if bit == 0:
        return ""  # handled by null unpacker

    lines = []
    lines.append("static void __SIMD_fastunpack%d_16(const __m128i *in, uint16_t *_out, __m128i* sum) {" % bit)
    lines.append("  (void)_out;")
    lines.append("  __m128i InReg = _mm_loadu_si128(in);")
    lines.append("  __m128i OutReg;")

    if bit == LANE_BITS:
        # bit=16: each input word IS the values, just aggregate
        lines.pop()  # remove "  __m128i OutReg;"
        lines.append("  aggregate_sums_u16(InReg, sum);")
        for i in range(1, BLOCK // LANES):
            lines.append("  InReg = _mm_loadu_si128(++in);")
            lines.append("  aggregate_sums_u16(InReg, sum);")
        lines.append("}")
        lines.append("")
        return "\n".join(lines)

    lines.append("  const __m128i mask = _mm_set1_epi16((1U << %d) - 1);" % bit)
    lines.append("")

    # Track position within packed data
    in_word = 0        # current input word index
    bit_pos = 0        # bit offset within current word's lane
    total_values = BLOCK // LANES  # 16 groups of 8 values = 128 values total

    for v in range(total_values):
        remaining_in_word = LANE_BITS - bit_pos

        if remaining_in_word >= bit:
            # Full value available in current word
            if bit_pos == 0:
                lines.append("  OutReg = _mm_and_si128(InReg, mask);")
            else:
                lines.append("  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, %d), mask);" % bit_pos)
            lines.append("  aggregate_sums_u16(OutReg, sum);")
            lines.append("")
            bit_pos += bit
        else:
            # Value spans two input words
            if remaining_in_word > 0:
                lines.append("  OutReg = _mm_srli_epi16(InReg, %d);" % bit_pos)
            lines.append("  InReg = _mm_loadu_si128(++in);")
            in_word += 1

            consumed = remaining_in_word
            need = bit - consumed

            if consumed > 0:
                lines.append("  OutReg =")
                lines.append("      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, %d - %d), mask));" % (bit, need))
            else:
                lines.append("  OutReg = _mm_and_si128(InReg, mask);")

            lines.append("  aggregate_sums_u16(OutReg, sum);")
            lines.append("")
            bit_pos = need

        if bit_pos == LANE_BITS:
            # Exactly consumed the whole word, load next if not last
            if v < total_values - 1:
                lines.append("  InReg = _mm_loadu_si128(++in);")
                in_word += 1
            bit_pos = 0

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def gen_pack_dispatcher():
    lines = []
    lines.append("void simdpack_u16(const uint16_t *in, __m128i *out, const uint32_t bit) {")
    lines.append("  switch (bit) {")
    for b in range(MAX_BIT + 1):
        lines.append("  case %d:" % b)
        if b == 0:
            lines.append("    __SIMD_fastpackwithoutmask0_16(in, out);")
        else:
            lines.append("    __SIMD_fastpackwithoutmask%d_16(in, out);" % b)
        lines.append("    return;")
        lines.append("")
    lines.append("  default:")
    lines.append("    break;")
    lines.append("  }")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def gen_unpack_dispatcher():
    lines = []
    lines.append("void simdunpack_u16(const __m128i *in, uint16_t *out, const uint32_t bit, __m128i* sum) {")
    lines.append("  switch (bit) {")
    lines.append("  case 0:")
    lines.append("    SIMD_nullunpacker16(in, out);")
    lines.append("    break;")
    lines.append("")
    for b in range(1, MAX_BIT + 1):
        lines.append("  case %d:" % b)
        lines.append("    __SIMD_fastunpack%d_16(in, out, sum);" % b)
        lines.append("    break;")
        lines.append("")
    lines.append("  default:")
    lines.append("    break;")
    lines.append("  }")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def gen_shortlength_pack():
    """Generic short-length packer for remainders < SIMDBlockSize."""
    return """\
__m128i *simdpack_shortlength_u16(const uint16_t *in, int length, __m128i *out,
                                   const uint32_t bit) {
  int k;
  int inwordpointer;
  __m128i P;
  uint32_t firstpass;
  if (bit == 0)
    return out;
  if (bit == 16) {
    memcpy(out, in, length * sizeof(uint16_t));
    return (__m128i *)((uint16_t *)out + length);
  }
  inwordpointer = 0;
  P = _mm_setzero_si128();
  for (k = 0; k < length / 8; ++k) {
    __m128i value = _mm_loadu_si128(((const __m128i *)in + k));
    P = _mm_or_si128(P, _mm_slli_epi16(value, inwordpointer));
    firstpass = 16 - inwordpointer;
    if (bit < firstpass) {
      inwordpointer += bit;
    } else {
      _mm_storeu_si128(out++, P);
      P = _mm_srli_epi16(value, firstpass);
      inwordpointer = bit - firstpass;
    }
  }
  if (length % 8 != 0) {
    uint16_t buffer[8];
    __m128i value;
    for (k = 0; k < (length % 8); ++k) {
      buffer[k] = in[length / 8 * 8 + k];
    }
    for (k = (length % 8); k < 8; ++k) {
      buffer[k] = 0;
    }
    value = _mm_loadu_si128((__m128i *)buffer);
    P = _mm_or_si128(P, _mm_slli_epi16(value, inwordpointer));
    firstpass = 16 - inwordpointer;
    if (bit < firstpass) {
      inwordpointer += bit;
    } else {
      _mm_storeu_si128(out++, P);
      P = _mm_srli_epi16(value, firstpass);
      inwordpointer = bit - firstpass;
    }
  }
  if (inwordpointer != 0) {
    _mm_storeu_si128(out++, P);
  }
  return out;
}

"""


def gen_shortlength_unpack():
    """Generic short-length unpacker for remainders < SIMDBlockSize."""
    return """\
const __m128i *simdunpack_shortlength_u16(const __m128i *in, int length,
                                           uint16_t *out, const uint32_t bit) {
  int k;
  __m128i maskbits;
  int inwordpointer;
  __m128i P;
  if (length == 0)
    return in;
  if (bit == 0) {
    for (k = 0; k < length; ++k) {
      out[k] = 0;
    }
    return in;
  }
  if (bit == 16) {
    memcpy(out, in, length * sizeof(uint16_t));
    return (const __m128i *)((uint16_t *)in + length);
  }
  maskbits = _mm_set1_epi16((1U << bit) - 1);
  inwordpointer = 0;
  P = _mm_loadu_si128((__m128i *)in);
  ++in;
  if (length % 8 == 0) {
    for (k = 0; k + 1 < length / 8; ++k) {
      __m128i answer = _mm_srli_epi16(P, inwordpointer);
      const uint32_t firstpass = 16 - inwordpointer;
      if (bit < firstpass) {
        inwordpointer += bit;
      } else {
        P = _mm_loadu_si128((__m128i *)in);
        ++in;
        answer = _mm_or_si128(_mm_slli_epi16(P, firstpass), answer);
        inwordpointer = bit - firstpass;
      }
      answer = _mm_and_si128(maskbits, answer);
      _mm_storeu_si128((__m128i *)out, answer);
      out += 8;
    }
    if (k < length / 8) {
      __m128i answer = _mm_srli_epi16(P, inwordpointer);
      const uint32_t firstpass = 16 - inwordpointer;
      if (bit < firstpass) {
        inwordpointer += bit;
      } else if (bit == firstpass) {
        inwordpointer = 0;
      } else {
        P = _mm_loadu_si128((__m128i *)in);
        ++in;
        answer = _mm_or_si128(_mm_slli_epi16(P, firstpass), answer);
        inwordpointer = bit - firstpass;
      }
      answer = _mm_and_si128(maskbits, answer);
      _mm_storeu_si128((__m128i *)out, answer);
      out += 8;
    }
  } else {
    for (k = 0; k < length / 8; ++k) {
      __m128i answer = _mm_srli_epi16(P, inwordpointer);
      const uint32_t firstpass = 16 - inwordpointer;
      if (bit < firstpass) {
        inwordpointer += bit;
      } else {
        P = _mm_loadu_si128((__m128i *)in);
        ++in;
        answer = _mm_or_si128(_mm_slli_epi16(P, firstpass), answer);
        inwordpointer = bit - firstpass;
      }
      answer = _mm_and_si128(maskbits, answer);
      _mm_storeu_si128((__m128i *)out, answer);
      out += 8;
    }
    uint16_t buffer[8];
    __m128i answer = _mm_srli_epi16(P, inwordpointer);
    const uint32_t firstpass = 16 - inwordpointer;
    if (bit < firstpass) {
      inwordpointer += bit;
    } else if (bit == firstpass) {
      inwordpointer = 0;
    } else {
      P = _mm_loadu_si128((__m128i *)in);
      ++in;
      answer = _mm_or_si128(_mm_slli_epi16(P, firstpass), answer);
      inwordpointer = bit - firstpass;
    }
    answer = _mm_and_si128(maskbits, answer);
    _mm_storeu_si128((__m128i *)buffer, answer);
    for (k = 0; k < (length % 8); ++k) {
      *out = buffer[k];
      ++out;
    }
  }
  return in;
}

"""


def gen_utility_functions():
    return """\
/* returns the integer logarithm of v (bit width) for uint16 */
static uint32_t bits_u16(const uint16_t v) {
  return v == 0 ? 0 : 32 - __builtin_clz((uint32_t)v);
}

static uint32_t oras_u16(const __m128i accumulator) {
  /* Horizontal OR of 8 uint16 lanes into a single uint16 value */
  const __m128i _tmp1 = _mm_or_si128(
      _mm_srli_si128(accumulator, 8), accumulator);
  const __m128i _tmp2 = _mm_or_si128(
      _mm_srli_si128(_tmp1, 4), _tmp1);
  const __m128i _tmp3 = _mm_or_si128(
      _mm_srli_si128(_tmp2, 2), _tmp2);
  return (uint16_t)_mm_extract_epi16(_tmp3, 0);
}

uint32_t maxbits_length_u16(const uint16_t *in, size_t length) {
  size_t k;
  size_t lengthdividedby8 = length / 8;
  size_t offset = lengthdividedby8 * 8;
  uint32_t bigxor = 0;
  if (lengthdividedby8 > 0) {
    const __m128i *pin = (const __m128i *)(in);
    __m128i accumulator = _mm_loadu_si128(pin);
    k = 1;
    for (; 8 * k < 8 * lengthdividedby8; ++k) {
      __m128i newvec = _mm_loadu_si128(pin + k);
      accumulator = _mm_or_si128(accumulator, newvec);
    }
    bigxor = oras_u16(accumulator);
  }
  for (k = offset; k < length; ++k)
    bigxor |= in[k];
  return bits_u16((uint16_t)bigxor);
}

int simdpack_compressedbytes_u16(int length, const uint32_t bit) {
  if (bit == 0)
    return 0;
  if (bit == 16) {
    return length * sizeof(uint16_t);
  }
  /* Each group of 8 uint16 lanes packs to (8 * bit) bits = bit bytes per group.
     Total groups = (length + 7) / 8.  Round up to __m128i boundary. */
  return (((length + 7) / 8) * bit + 15) / 16 * sizeof(__m128i);
}

__m128i *simdpack_length_u16(const uint16_t *in, size_t length, __m128i *out,
                              const uint32_t bit) {
  size_t k;
  for (k = 0; k < length / SIMDBlockSize_u16; ++k) {
    simdpack_u16(in, out, bit);
    in += SIMDBlockSize_u16;
    out += bit;
  }
  return simdpack_shortlength_u16(in, length % SIMDBlockSize_u16, out, bit);
}

const __m128i *simdunpack_length_u16(const __m128i *in, size_t length,
                                      uint16_t *out, const uint32_t bit,
                                      uint32_t *outsum) {
  __m128i sum = _mm_setzero_si128();
  size_t k;
  for (k = 0; k < length / SIMDBlockSize_u16; ++k) {
    simdunpack_u16(in, out, bit, &sum);
    out += SIMDBlockSize_u16;
    in += bit;
  }
  /* Horizontal reduction: 4 x int32 -> 1 x int32 */
  __m128i s = sum;
  s = _mm_add_epi32(s, _mm_shuffle_epi32(s, _MM_SHUFFLE(1,0,3,2)));
  s = _mm_add_epi32(s, _mm_shuffle_epi32(s, _MM_SHUFFLE(2,3,0,1)));

  uint32_t finalsum = (uint32_t)_mm_cvtsi128_si32(s);

  /* Handle remainder with scalar sum */
  size_t remainder = length % SIMDBlockSize_u16;
  if (remainder > 0) {
    in = simdunpack_shortlength_u16(in, remainder, out, bit);
    size_t i;
    for (i = 0; i < remainder; ++i) {
      finalsum += out[i];
    }
  }
  *outsum = finalsum;
  return in;
}

"""


def main():
    out = []
    out.append(gen_header())
    out.append(gen_null_unpacker())

    # Pack functions for all bit widths
    for bit in range(MAX_BIT + 1):
        out.append(gen_pack_function(bit))

    out.append(gen_pack_dispatcher())

    # Unpack+sum functions for all bit widths
    for bit in range(1, MAX_BIT + 1):
        out.append(gen_unpack_function(bit))

    out.append(gen_unpack_dispatcher())

    # Short-length handlers
    out.append(gen_shortlength_pack())
    out.append(gen_shortlength_unpack())

    # Utility functions
    out.append(gen_utility_functions())

    print("".join(out))


if __name__ == "__main__":
    main()
