/**
 * Auto-generated uint16 SIMD bit-packing with fused sum aggregation.
 * Generated by gen_simdbitpacking_u16.py
 *
 * This code is released under a BSD License.
 */
#include "simdbitpacking_u16.h"
#include <string.h>

#define SIMDBlockSize_u16 128

static const __m128i ones_u16 = {0x0001000100010001ULL, 0x0001000100010001ULL};

static void aggregate_sums_u16(__m128i OutReg, __m128i* sum) {
    /* Widen 8 x uint16 -> 4 x int32 via pairwise multiply-add, then accumulate.
       Correct when all uint16 values <= 32767 (i.e. data fits signed int16).
       2 instructions / 8 values = 0.25 inst/val. */
    *sum = _mm_add_epi32(*sum, _mm_madd_epi16(OutReg, ones_u16));
}

static void SIMD_nullunpacker16(const __m128i *_in, uint16_t *out) {
  (void)_in;
  memset(out, 0, 128 * sizeof(uint16_t));
}

static void __SIMD_fastpackwithoutmask0_16(const uint16_t *_in, __m128i *out) {
  (void)out;
  (void)_in;
}

static void __SIMD_fastpackwithoutmask1_16(const uint16_t *_in, __m128i *out) {
  const __m128i *in = (const __m128i *)(_in);
  __m128i OutReg;
  __m128i InReg = _mm_loadu_si128(in);

  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 1));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 2));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 3));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 5));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 6));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 7));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 9));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 10));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 11));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 13));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 14));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 15));
  _mm_storeu_si128(out + 0, OutReg);
}
static void __SIMD_fastpackwithoutmask2_16(const uint16_t *_in, __m128i *out) {
  const __m128i *in = (const __m128i *)(_in);
  __m128i OutReg;
  __m128i InReg = _mm_loadu_si128(in);

  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 2));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 6));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 10));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 14));
  _mm_storeu_si128(out + 0, OutReg);
  InReg = _mm_loadu_si128(++in);
  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 2));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 6));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 10));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 14));
  _mm_storeu_si128(out + 1, OutReg);
}
static void __SIMD_fastpackwithoutmask3_16(const uint16_t *_in, __m128i *out) {
  const __m128i *in = (const __m128i *)(_in);
  __m128i OutReg;
  __m128i InReg = _mm_loadu_si128(in);

  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 3));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 6));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 9));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 15));
  _mm_storeu_si128(out + 0, OutReg);
  OutReg = _mm_srli_epi16(InReg, 1);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 2));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 5));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 11));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 14));
  _mm_storeu_si128(out + 1, OutReg);
  OutReg = _mm_srli_epi16(InReg, 2);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 1));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 7));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 10));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 13));
  _mm_storeu_si128(out + 2, OutReg);
}
static void __SIMD_fastpackwithoutmask4_16(const uint16_t *_in, __m128i *out) {
  const __m128i *in = (const __m128i *)(_in);
  __m128i OutReg;
  __m128i InReg = _mm_loadu_si128(in);

  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  _mm_storeu_si128(out + 0, OutReg);
  InReg = _mm_loadu_si128(++in);
  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  _mm_storeu_si128(out + 1, OutReg);
  InReg = _mm_loadu_si128(++in);
  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  _mm_storeu_si128(out + 2, OutReg);
  InReg = _mm_loadu_si128(++in);
  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  _mm_storeu_si128(out + 3, OutReg);
}
static void __SIMD_fastpackwithoutmask5_16(const uint16_t *_in, __m128i *out) {
  const __m128i *in = (const __m128i *)(_in);
  __m128i OutReg;
  __m128i InReg = _mm_loadu_si128(in);

  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 5));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 10));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 15));
  _mm_storeu_si128(out + 0, OutReg);
  OutReg = _mm_srli_epi16(InReg, 1);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 9));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 14));
  _mm_storeu_si128(out + 1, OutReg);
  OutReg = _mm_srli_epi16(InReg, 2);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 3));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 13));
  _mm_storeu_si128(out + 2, OutReg);
  OutReg = _mm_srli_epi16(InReg, 3);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 2));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 7));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  _mm_storeu_si128(out + 3, OutReg);
  OutReg = _mm_srli_epi16(InReg, 4);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 1));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 6));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 11));
  _mm_storeu_si128(out + 4, OutReg);
}
static void __SIMD_fastpackwithoutmask6_16(const uint16_t *_in, __m128i *out) {
  const __m128i *in = (const __m128i *)(_in);
  __m128i OutReg;
  __m128i InReg = _mm_loadu_si128(in);

  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 6));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  _mm_storeu_si128(out + 0, OutReg);
  OutReg = _mm_srli_epi16(InReg, 4);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 2));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 14));
  _mm_storeu_si128(out + 1, OutReg);
  OutReg = _mm_srli_epi16(InReg, 2);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 10));
  _mm_storeu_si128(out + 2, OutReg);
  InReg = _mm_loadu_si128(++in);
  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 6));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  _mm_storeu_si128(out + 3, OutReg);
  OutReg = _mm_srli_epi16(InReg, 4);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 2));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 14));
  _mm_storeu_si128(out + 4, OutReg);
  OutReg = _mm_srli_epi16(InReg, 2);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 10));
  _mm_storeu_si128(out + 5, OutReg);
}
static void __SIMD_fastpackwithoutmask7_16(const uint16_t *_in, __m128i *out) {
  const __m128i *in = (const __m128i *)(_in);
  __m128i OutReg;
  __m128i InReg = _mm_loadu_si128(in);

  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 7));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 14));
  _mm_storeu_si128(out + 0, OutReg);
  OutReg = _mm_srli_epi16(InReg, 2);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 5));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  _mm_storeu_si128(out + 1, OutReg);
  OutReg = _mm_srli_epi16(InReg, 4);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 3));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 10));
  _mm_storeu_si128(out + 2, OutReg);
  OutReg = _mm_srli_epi16(InReg, 6);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 1));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 15));
  _mm_storeu_si128(out + 3, OutReg);
  OutReg = _mm_srli_epi16(InReg, 1);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 6));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 13));
  _mm_storeu_si128(out + 4, OutReg);
  OutReg = _mm_srli_epi16(InReg, 3);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 11));
  _mm_storeu_si128(out + 5, OutReg);
  OutReg = _mm_srli_epi16(InReg, 5);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 2));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 9));
  _mm_storeu_si128(out + 6, OutReg);
}
static void __SIMD_fastpackwithoutmask8_16(const uint16_t *_in, __m128i *out) {
  const __m128i *in = (const __m128i *)(_in);
  __m128i OutReg;
  __m128i InReg = _mm_loadu_si128(in);

  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  _mm_storeu_si128(out + 0, OutReg);
  InReg = _mm_loadu_si128(++in);
  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  _mm_storeu_si128(out + 1, OutReg);
  InReg = _mm_loadu_si128(++in);
  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  _mm_storeu_si128(out + 2, OutReg);
  InReg = _mm_loadu_si128(++in);
  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  _mm_storeu_si128(out + 3, OutReg);
  InReg = _mm_loadu_si128(++in);
  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  _mm_storeu_si128(out + 4, OutReg);
  InReg = _mm_loadu_si128(++in);
  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  _mm_storeu_si128(out + 5, OutReg);
  InReg = _mm_loadu_si128(++in);
  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  _mm_storeu_si128(out + 6, OutReg);
  InReg = _mm_loadu_si128(++in);
  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  _mm_storeu_si128(out + 7, OutReg);
}
static void __SIMD_fastpackwithoutmask9_16(const uint16_t *_in, __m128i *out) {
  const __m128i *in = (const __m128i *)(_in);
  __m128i OutReg;
  __m128i InReg = _mm_loadu_si128(in);

  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 9));
  _mm_storeu_si128(out + 0, OutReg);
  OutReg = _mm_srli_epi16(InReg, 7);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 2));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 11));
  _mm_storeu_si128(out + 1, OutReg);
  OutReg = _mm_srli_epi16(InReg, 5);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 13));
  _mm_storeu_si128(out + 2, OutReg);
  OutReg = _mm_srli_epi16(InReg, 3);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 6));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 15));
  _mm_storeu_si128(out + 3, OutReg);
  OutReg = _mm_srli_epi16(InReg, 1);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  _mm_storeu_si128(out + 4, OutReg);
  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 1));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 10));
  _mm_storeu_si128(out + 5, OutReg);
  OutReg = _mm_srli_epi16(InReg, 6);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 3));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  _mm_storeu_si128(out + 6, OutReg);
  OutReg = _mm_srli_epi16(InReg, 4);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 5));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 14));
  _mm_storeu_si128(out + 7, OutReg);
  OutReg = _mm_srli_epi16(InReg, 2);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 7));
  _mm_storeu_si128(out + 8, OutReg);
}
static void __SIMD_fastpackwithoutmask10_16(const uint16_t *_in, __m128i *out) {
  const __m128i *in = (const __m128i *)(_in);
  __m128i OutReg;
  __m128i InReg = _mm_loadu_si128(in);

  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 10));
  _mm_storeu_si128(out + 0, OutReg);
  OutReg = _mm_srli_epi16(InReg, 6);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 14));
  _mm_storeu_si128(out + 1, OutReg);
  OutReg = _mm_srli_epi16(InReg, 2);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  _mm_storeu_si128(out + 2, OutReg);
  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 2));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  _mm_storeu_si128(out + 3, OutReg);
  OutReg = _mm_srli_epi16(InReg, 4);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 6));
  _mm_storeu_si128(out + 4, OutReg);
  InReg = _mm_loadu_si128(++in);
  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 10));
  _mm_storeu_si128(out + 5, OutReg);
  OutReg = _mm_srli_epi16(InReg, 6);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 14));
  _mm_storeu_si128(out + 6, OutReg);
  OutReg = _mm_srli_epi16(InReg, 2);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  _mm_storeu_si128(out + 7, OutReg);
  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 2));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  _mm_storeu_si128(out + 8, OutReg);
  OutReg = _mm_srli_epi16(InReg, 4);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 6));
  _mm_storeu_si128(out + 9, OutReg);
}
static void __SIMD_fastpackwithoutmask11_16(const uint16_t *_in, __m128i *out) {
  const __m128i *in = (const __m128i *)(_in);
  __m128i OutReg;
  __m128i InReg = _mm_loadu_si128(in);

  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 11));
  _mm_storeu_si128(out + 0, OutReg);
  OutReg = _mm_srli_epi16(InReg, 5);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 6));
  _mm_storeu_si128(out + 1, OutReg);
  OutReg = _mm_srli_epi16(InReg, 10);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 1));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  _mm_storeu_si128(out + 2, OutReg);
  OutReg = _mm_srli_epi16(InReg, 4);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 7));
  _mm_storeu_si128(out + 3, OutReg);
  OutReg = _mm_srli_epi16(InReg, 9);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 2));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 13));
  _mm_storeu_si128(out + 4, OutReg);
  OutReg = _mm_srli_epi16(InReg, 3);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  _mm_storeu_si128(out + 5, OutReg);
  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 3));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 14));
  _mm_storeu_si128(out + 6, OutReg);
  OutReg = _mm_srli_epi16(InReg, 2);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 9));
  _mm_storeu_si128(out + 7, OutReg);
  OutReg = _mm_srli_epi16(InReg, 7);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 15));
  _mm_storeu_si128(out + 8, OutReg);
  OutReg = _mm_srli_epi16(InReg, 1);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 10));
  _mm_storeu_si128(out + 9, OutReg);
  OutReg = _mm_srli_epi16(InReg, 6);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 5));
  _mm_storeu_si128(out + 10, OutReg);
}
static void __SIMD_fastpackwithoutmask12_16(const uint16_t *_in, __m128i *out) {
  const __m128i *in = (const __m128i *)(_in);
  __m128i OutReg;
  __m128i InReg = _mm_loadu_si128(in);

  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  _mm_storeu_si128(out + 0, OutReg);
  OutReg = _mm_srli_epi16(InReg, 4);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  _mm_storeu_si128(out + 1, OutReg);
  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  _mm_storeu_si128(out + 2, OutReg);
  InReg = _mm_loadu_si128(++in);
  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  _mm_storeu_si128(out + 3, OutReg);
  OutReg = _mm_srli_epi16(InReg, 4);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  _mm_storeu_si128(out + 4, OutReg);
  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  _mm_storeu_si128(out + 5, OutReg);
  InReg = _mm_loadu_si128(++in);
  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  _mm_storeu_si128(out + 6, OutReg);
  OutReg = _mm_srli_epi16(InReg, 4);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  _mm_storeu_si128(out + 7, OutReg);
  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  _mm_storeu_si128(out + 8, OutReg);
  InReg = _mm_loadu_si128(++in);
  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  _mm_storeu_si128(out + 9, OutReg);
  OutReg = _mm_srli_epi16(InReg, 4);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  _mm_storeu_si128(out + 10, OutReg);
  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  _mm_storeu_si128(out + 11, OutReg);
}
static void __SIMD_fastpackwithoutmask13_16(const uint16_t *_in, __m128i *out) {
  const __m128i *in = (const __m128i *)(_in);
  __m128i OutReg;
  __m128i InReg = _mm_loadu_si128(in);

  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 13));
  _mm_storeu_si128(out + 0, OutReg);
  OutReg = _mm_srli_epi16(InReg, 3);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 10));
  _mm_storeu_si128(out + 1, OutReg);
  OutReg = _mm_srli_epi16(InReg, 6);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 7));
  _mm_storeu_si128(out + 2, OutReg);
  OutReg = _mm_srli_epi16(InReg, 9);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  _mm_storeu_si128(out + 3, OutReg);
  OutReg = _mm_srli_epi16(InReg, 12);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 1));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 14));
  _mm_storeu_si128(out + 4, OutReg);
  OutReg = _mm_srli_epi16(InReg, 2);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 11));
  _mm_storeu_si128(out + 5, OutReg);
  OutReg = _mm_srli_epi16(InReg, 5);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  _mm_storeu_si128(out + 6, OutReg);
  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 5));
  _mm_storeu_si128(out + 7, OutReg);
  OutReg = _mm_srli_epi16(InReg, 11);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 2));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 15));
  _mm_storeu_si128(out + 8, OutReg);
  OutReg = _mm_srli_epi16(InReg, 1);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  _mm_storeu_si128(out + 9, OutReg);
  OutReg = _mm_srli_epi16(InReg, 4);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 9));
  _mm_storeu_si128(out + 10, OutReg);
  OutReg = _mm_srli_epi16(InReg, 7);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 6));
  _mm_storeu_si128(out + 11, OutReg);
  OutReg = _mm_srli_epi16(InReg, 10);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 3));
  _mm_storeu_si128(out + 12, OutReg);
}
static void __SIMD_fastpackwithoutmask14_16(const uint16_t *_in, __m128i *out) {
  const __m128i *in = (const __m128i *)(_in);
  __m128i OutReg;
  __m128i InReg = _mm_loadu_si128(in);

  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 14));
  _mm_storeu_si128(out + 0, OutReg);
  OutReg = _mm_srli_epi16(InReg, 2);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  _mm_storeu_si128(out + 1, OutReg);
  OutReg = _mm_srli_epi16(InReg, 4);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 10));
  _mm_storeu_si128(out + 2, OutReg);
  OutReg = _mm_srli_epi16(InReg, 6);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  _mm_storeu_si128(out + 3, OutReg);
  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 6));
  _mm_storeu_si128(out + 4, OutReg);
  OutReg = _mm_srli_epi16(InReg, 10);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  _mm_storeu_si128(out + 5, OutReg);
  OutReg = _mm_srli_epi16(InReg, 12);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 2));
  _mm_storeu_si128(out + 6, OutReg);
  InReg = _mm_loadu_si128(++in);
  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 14));
  _mm_storeu_si128(out + 7, OutReg);
  OutReg = _mm_srli_epi16(InReg, 2);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  _mm_storeu_si128(out + 8, OutReg);
  OutReg = _mm_srli_epi16(InReg, 4);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 10));
  _mm_storeu_si128(out + 9, OutReg);
  OutReg = _mm_srli_epi16(InReg, 6);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  _mm_storeu_si128(out + 10, OutReg);
  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 6));
  _mm_storeu_si128(out + 11, OutReg);
  OutReg = _mm_srli_epi16(InReg, 10);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  _mm_storeu_si128(out + 12, OutReg);
  OutReg = _mm_srli_epi16(InReg, 12);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 2));
  _mm_storeu_si128(out + 13, OutReg);
}
static void __SIMD_fastpackwithoutmask15_16(const uint16_t *_in, __m128i *out) {
  const __m128i *in = (const __m128i *)(_in);
  __m128i OutReg;
  __m128i InReg = _mm_loadu_si128(in);

  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 15));
  _mm_storeu_si128(out + 0, OutReg);
  OutReg = _mm_srli_epi16(InReg, 1);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 14));
  _mm_storeu_si128(out + 1, OutReg);
  OutReg = _mm_srli_epi16(InReg, 2);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 13));
  _mm_storeu_si128(out + 2, OutReg);
  OutReg = _mm_srli_epi16(InReg, 3);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  _mm_storeu_si128(out + 3, OutReg);
  OutReg = _mm_srli_epi16(InReg, 4);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 11));
  _mm_storeu_si128(out + 4, OutReg);
  OutReg = _mm_srli_epi16(InReg, 5);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 10));
  _mm_storeu_si128(out + 5, OutReg);
  OutReg = _mm_srli_epi16(InReg, 6);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 9));
  _mm_storeu_si128(out + 6, OutReg);
  OutReg = _mm_srli_epi16(InReg, 7);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  _mm_storeu_si128(out + 7, OutReg);
  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 7));
  _mm_storeu_si128(out + 8, OutReg);
  OutReg = _mm_srli_epi16(InReg, 9);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 6));
  _mm_storeu_si128(out + 9, OutReg);
  OutReg = _mm_srli_epi16(InReg, 10);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 5));
  _mm_storeu_si128(out + 10, OutReg);
  OutReg = _mm_srli_epi16(InReg, 11);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  _mm_storeu_si128(out + 11, OutReg);
  OutReg = _mm_srli_epi16(InReg, 12);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 3));
  _mm_storeu_si128(out + 12, OutReg);
  OutReg = _mm_srli_epi16(InReg, 13);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 2));
  _mm_storeu_si128(out + 13, OutReg);
  OutReg = _mm_srli_epi16(InReg, 14);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 1));
  _mm_storeu_si128(out + 14, OutReg);
}
static void __SIMD_fastpackwithoutmask16_16(const uint16_t *_in, __m128i *out) {
  const __m128i *in = (const __m128i *)(_in);
  __m128i OutReg;
  __m128i InReg = _mm_loadu_si128(in);
  _mm_storeu_si128(out, InReg);
  InReg = _mm_loadu_si128(++in);
  _mm_storeu_si128(out + 1, InReg);
  InReg = _mm_loadu_si128(++in);
  _mm_storeu_si128(out + 2, InReg);
  InReg = _mm_loadu_si128(++in);
  _mm_storeu_si128(out + 3, InReg);
  InReg = _mm_loadu_si128(++in);
  _mm_storeu_si128(out + 4, InReg);
  InReg = _mm_loadu_si128(++in);
  _mm_storeu_si128(out + 5, InReg);
  InReg = _mm_loadu_si128(++in);
  _mm_storeu_si128(out + 6, InReg);
  InReg = _mm_loadu_si128(++in);
  _mm_storeu_si128(out + 7, InReg);
  InReg = _mm_loadu_si128(++in);
  _mm_storeu_si128(out + 8, InReg);
  InReg = _mm_loadu_si128(++in);
  _mm_storeu_si128(out + 9, InReg);
  InReg = _mm_loadu_si128(++in);
  _mm_storeu_si128(out + 10, InReg);
  InReg = _mm_loadu_si128(++in);
  _mm_storeu_si128(out + 11, InReg);
  InReg = _mm_loadu_si128(++in);
  _mm_storeu_si128(out + 12, InReg);
  InReg = _mm_loadu_si128(++in);
  _mm_storeu_si128(out + 13, InReg);
  InReg = _mm_loadu_si128(++in);
  _mm_storeu_si128(out + 14, InReg);
  InReg = _mm_loadu_si128(++in);
  _mm_storeu_si128(out + 15, InReg);
}
void simdpack_u16(const uint16_t *in, __m128i *out, const uint32_t bit) {
  switch (bit) {
  case 0:
    __SIMD_fastpackwithoutmask0_16(in, out);
    return;

  case 1:
    __SIMD_fastpackwithoutmask1_16(in, out);
    return;

  case 2:
    __SIMD_fastpackwithoutmask2_16(in, out);
    return;

  case 3:
    __SIMD_fastpackwithoutmask3_16(in, out);
    return;

  case 4:
    __SIMD_fastpackwithoutmask4_16(in, out);
    return;

  case 5:
    __SIMD_fastpackwithoutmask5_16(in, out);
    return;

  case 6:
    __SIMD_fastpackwithoutmask6_16(in, out);
    return;

  case 7:
    __SIMD_fastpackwithoutmask7_16(in, out);
    return;

  case 8:
    __SIMD_fastpackwithoutmask8_16(in, out);
    return;

  case 9:
    __SIMD_fastpackwithoutmask9_16(in, out);
    return;

  case 10:
    __SIMD_fastpackwithoutmask10_16(in, out);
    return;

  case 11:
    __SIMD_fastpackwithoutmask11_16(in, out);
    return;

  case 12:
    __SIMD_fastpackwithoutmask12_16(in, out);
    return;

  case 13:
    __SIMD_fastpackwithoutmask13_16(in, out);
    return;

  case 14:
    __SIMD_fastpackwithoutmask14_16(in, out);
    return;

  case 15:
    __SIMD_fastpackwithoutmask15_16(in, out);
    return;

  case 16:
    __SIMD_fastpackwithoutmask16_16(in, out);
    return;

  default:
    break;
  }
}
static void __SIMD_fastunpack1_16(const __m128i *in, uint16_t *_out, __m128i* sum) {
  (void)_out;
  __m128i InReg = _mm_loadu_si128(in);
  __m128i OutReg;
  const __m128i mask = _mm_set1_epi16((1U << 1) - 1);

  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 1), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 2), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 3), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 4), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 5), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 6), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 7), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 8), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 9), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 10), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 11), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 12), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 13), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 14), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 15), mask);
  aggregate_sums_u16(OutReg, sum);

}
static void __SIMD_fastunpack2_16(const __m128i *in, uint16_t *_out, __m128i* sum) {
  (void)_out;
  __m128i InReg = _mm_loadu_si128(in);
  __m128i OutReg;
  const __m128i mask = _mm_set1_epi16((1U << 2) - 1);

  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 2), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 4), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 6), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 8), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 10), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 12), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 14), mask);
  aggregate_sums_u16(OutReg, sum);

  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 2), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 4), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 6), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 8), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 10), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 12), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 14), mask);
  aggregate_sums_u16(OutReg, sum);

}
static void __SIMD_fastunpack3_16(const __m128i *in, uint16_t *_out, __m128i* sum) {
  (void)_out;
  __m128i InReg = _mm_loadu_si128(in);
  __m128i OutReg;
  const __m128i mask = _mm_set1_epi16((1U << 3) - 1);

  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 3), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 6), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 9), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 12), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 15);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 3 - 2), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 2), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 5), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 8), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 11), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 14);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 3 - 1), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 1), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 4), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 7), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 10), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 13), mask);
  aggregate_sums_u16(OutReg, sum);

}
static void __SIMD_fastunpack4_16(const __m128i *in, uint16_t *_out, __m128i* sum) {
  (void)_out;
  __m128i InReg = _mm_loadu_si128(in);
  __m128i OutReg;
  const __m128i mask = _mm_set1_epi16((1U << 4) - 1);

  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 4), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 8), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 12), mask);
  aggregate_sums_u16(OutReg, sum);

  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 4), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 8), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 12), mask);
  aggregate_sums_u16(OutReg, sum);

  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 4), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 8), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 12), mask);
  aggregate_sums_u16(OutReg, sum);

  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 4), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 8), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 12), mask);
  aggregate_sums_u16(OutReg, sum);

}
static void __SIMD_fastunpack5_16(const __m128i *in, uint16_t *_out, __m128i* sum) {
  (void)_out;
  __m128i InReg = _mm_loadu_si128(in);
  __m128i OutReg;
  const __m128i mask = _mm_set1_epi16((1U << 5) - 1);

  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 5), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 10), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 15);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 5 - 4), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 4), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 9), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 14);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 5 - 3), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 3), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 8), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 13);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 5 - 2), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 2), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 7), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 12);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 5 - 1), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 1), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 6), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 11), mask);
  aggregate_sums_u16(OutReg, sum);

}
static void __SIMD_fastunpack6_16(const __m128i *in, uint16_t *_out, __m128i* sum) {
  (void)_out;
  __m128i InReg = _mm_loadu_si128(in);
  __m128i OutReg;
  const __m128i mask = _mm_set1_epi16((1U << 6) - 1);

  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 6), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 12);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 6 - 2), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 2), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 8), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 14);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 6 - 4), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 4), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 10), mask);
  aggregate_sums_u16(OutReg, sum);

  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 6), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 12);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 6 - 2), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 2), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 8), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 14);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 6 - 4), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 4), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 10), mask);
  aggregate_sums_u16(OutReg, sum);

}
static void __SIMD_fastunpack7_16(const __m128i *in, uint16_t *_out, __m128i* sum) {
  (void)_out;
  __m128i InReg = _mm_loadu_si128(in);
  __m128i OutReg;
  const __m128i mask = _mm_set1_epi16((1U << 7) - 1);

  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 7), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 14);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 7 - 5), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 5), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 12);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 7 - 3), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 3), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 10);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 7 - 1), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 1), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 8), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 15);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 7 - 6), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 6), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 13);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 7 - 4), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 4), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 11);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 7 - 2), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 2), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 9), mask);
  aggregate_sums_u16(OutReg, sum);

}
static void __SIMD_fastunpack8_16(const __m128i *in, uint16_t *_out, __m128i* sum) {
  (void)_out;
  __m128i InReg = _mm_loadu_si128(in);
  __m128i OutReg;
  const __m128i mask = _mm_set1_epi16((1U << 8) - 1);

  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 8), mask);
  aggregate_sums_u16(OutReg, sum);

  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 8), mask);
  aggregate_sums_u16(OutReg, sum);

  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 8), mask);
  aggregate_sums_u16(OutReg, sum);

  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 8), mask);
  aggregate_sums_u16(OutReg, sum);

  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 8), mask);
  aggregate_sums_u16(OutReg, sum);

  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 8), mask);
  aggregate_sums_u16(OutReg, sum);

  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 8), mask);
  aggregate_sums_u16(OutReg, sum);

  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 8), mask);
  aggregate_sums_u16(OutReg, sum);

}
static void __SIMD_fastunpack9_16(const __m128i *in, uint16_t *_out, __m128i* sum) {
  (void)_out;
  __m128i InReg = _mm_loadu_si128(in);
  __m128i OutReg;
  const __m128i mask = _mm_set1_epi16((1U << 9) - 1);

  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 9);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 9 - 2), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 2), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 11);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 9 - 4), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 4), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 13);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 9 - 6), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 6), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 15);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 9 - 8), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 9 - 1), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 1), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 10);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 9 - 3), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 3), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 12);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 9 - 5), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 5), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 14);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 9 - 7), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 7), mask);
  aggregate_sums_u16(OutReg, sum);

}
static void __SIMD_fastunpack10_16(const __m128i *in, uint16_t *_out, __m128i* sum) {
  (void)_out;
  __m128i InReg = _mm_loadu_si128(in);
  __m128i OutReg;
  const __m128i mask = _mm_set1_epi16((1U << 10) - 1);

  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 10);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 10 - 4), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 4), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 14);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 10 - 8), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 10 - 2), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 2), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 12);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 10 - 6), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 6), mask);
  aggregate_sums_u16(OutReg, sum);

  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 10);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 10 - 4), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 4), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 14);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 10 - 8), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 10 - 2), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 2), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 12);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 10 - 6), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 6), mask);
  aggregate_sums_u16(OutReg, sum);

}
static void __SIMD_fastunpack11_16(const __m128i *in, uint16_t *_out, __m128i* sum) {
  (void)_out;
  __m128i InReg = _mm_loadu_si128(in);
  __m128i OutReg;
  const __m128i mask = _mm_set1_epi16((1U << 11) - 1);

  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 11);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 11 - 6), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 6);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 11 - 1), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 1), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 12);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 11 - 7), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 7);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 11 - 2), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 2), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 13);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 11 - 8), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 11 - 3), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 3), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 14);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 11 - 9), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 9);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 11 - 4), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 4), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 15);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 11 - 10), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 10);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 11 - 5), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 5), mask);
  aggregate_sums_u16(OutReg, sum);

}
static void __SIMD_fastunpack12_16(const __m128i *in, uint16_t *_out, __m128i* sum) {
  (void)_out;
  __m128i InReg = _mm_loadu_si128(in);
  __m128i OutReg;
  const __m128i mask = _mm_set1_epi16((1U << 12) - 1);

  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 12);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 12 - 8), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 12 - 4), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 4), mask);
  aggregate_sums_u16(OutReg, sum);

  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 12);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 12 - 8), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 12 - 4), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 4), mask);
  aggregate_sums_u16(OutReg, sum);

  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 12);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 12 - 8), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 12 - 4), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 4), mask);
  aggregate_sums_u16(OutReg, sum);

  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 12);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 12 - 8), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 12 - 4), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 4), mask);
  aggregate_sums_u16(OutReg, sum);

}
static void __SIMD_fastunpack13_16(const __m128i *in, uint16_t *_out, __m128i* sum) {
  (void)_out;
  __m128i InReg = _mm_loadu_si128(in);
  __m128i OutReg;
  const __m128i mask = _mm_set1_epi16((1U << 13) - 1);

  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 13);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 13 - 10), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 10);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 13 - 7), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 7);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 13 - 4), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 4);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 13 - 1), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 1), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 14);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 13 - 11), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 11);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 13 - 8), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 13 - 5), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 5);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 13 - 2), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 2), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 15);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 13 - 12), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 12);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 13 - 9), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 9);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 13 - 6), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 6);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 13 - 3), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 3), mask);
  aggregate_sums_u16(OutReg, sum);

}
static void __SIMD_fastunpack14_16(const __m128i *in, uint16_t *_out, __m128i* sum) {
  (void)_out;
  __m128i InReg = _mm_loadu_si128(in);
  __m128i OutReg;
  const __m128i mask = _mm_set1_epi16((1U << 14) - 1);

  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 14);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 14 - 12), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 12);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 14 - 10), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 10);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 14 - 8), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 14 - 6), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 6);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 14 - 4), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 4);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 14 - 2), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 2), mask);
  aggregate_sums_u16(OutReg, sum);

  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 14);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 14 - 12), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 12);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 14 - 10), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 10);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 14 - 8), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 14 - 6), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 6);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 14 - 4), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 4);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 14 - 2), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 2), mask);
  aggregate_sums_u16(OutReg, sum);

}
static void __SIMD_fastunpack15_16(const __m128i *in, uint16_t *_out, __m128i* sum) {
  (void)_out;
  __m128i InReg = _mm_loadu_si128(in);
  __m128i OutReg;
  const __m128i mask = _mm_set1_epi16((1U << 15) - 1);

  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 15);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 15 - 14), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 14);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 15 - 13), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 13);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 15 - 12), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 12);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 15 - 11), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 11);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 15 - 10), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 10);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 15 - 9), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 9);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 15 - 8), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 15 - 7), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 7);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 15 - 6), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 6);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 15 - 5), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 5);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 15 - 4), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 4);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 15 - 3), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 3);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 15 - 2), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 2);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 15 - 1), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 1), mask);
  aggregate_sums_u16(OutReg, sum);

}
static void __SIMD_fastunpack16_16(const __m128i *in, uint16_t *_out, __m128i* sum) {
  (void)_out;
  __m128i InReg = _mm_loadu_si128(in);
  aggregate_sums_u16(InReg, sum);
  InReg = _mm_loadu_si128(++in);
  aggregate_sums_u16(InReg, sum);
  InReg = _mm_loadu_si128(++in);
  aggregate_sums_u16(InReg, sum);
  InReg = _mm_loadu_si128(++in);
  aggregate_sums_u16(InReg, sum);
  InReg = _mm_loadu_si128(++in);
  aggregate_sums_u16(InReg, sum);
  InReg = _mm_loadu_si128(++in);
  aggregate_sums_u16(InReg, sum);
  InReg = _mm_loadu_si128(++in);
  aggregate_sums_u16(InReg, sum);
  InReg = _mm_loadu_si128(++in);
  aggregate_sums_u16(InReg, sum);
  InReg = _mm_loadu_si128(++in);
  aggregate_sums_u16(InReg, sum);
  InReg = _mm_loadu_si128(++in);
  aggregate_sums_u16(InReg, sum);
  InReg = _mm_loadu_si128(++in);
  aggregate_sums_u16(InReg, sum);
  InReg = _mm_loadu_si128(++in);
  aggregate_sums_u16(InReg, sum);
  InReg = _mm_loadu_si128(++in);
  aggregate_sums_u16(InReg, sum);
  InReg = _mm_loadu_si128(++in);
  aggregate_sums_u16(InReg, sum);
  InReg = _mm_loadu_si128(++in);
  aggregate_sums_u16(InReg, sum);
  InReg = _mm_loadu_si128(++in);
  aggregate_sums_u16(InReg, sum);
}
void simdunpack_u16(const __m128i *in, uint16_t *out, const uint32_t bit, __m128i* sum) {
  switch (bit) {
  case 0:
    SIMD_nullunpacker16(in, out);
    break;

  case 1:
    __SIMD_fastunpack1_16(in, out, sum);
    break;

  case 2:
    __SIMD_fastunpack2_16(in, out, sum);
    break;

  case 3:
    __SIMD_fastunpack3_16(in, out, sum);
    break;

  case 4:
    __SIMD_fastunpack4_16(in, out, sum);
    break;

  case 5:
    __SIMD_fastunpack5_16(in, out, sum);
    break;

  case 6:
    __SIMD_fastunpack6_16(in, out, sum);
    break;

  case 7:
    __SIMD_fastunpack7_16(in, out, sum);
    break;

  case 8:
    __SIMD_fastunpack8_16(in, out, sum);
    break;

  case 9:
    __SIMD_fastunpack9_16(in, out, sum);
    break;

  case 10:
    __SIMD_fastunpack10_16(in, out, sum);
    break;

  case 11:
    __SIMD_fastunpack11_16(in, out, sum);
    break;

  case 12:
    __SIMD_fastunpack12_16(in, out, sum);
    break;

  case 13:
    __SIMD_fastunpack13_16(in, out, sum);
    break;

  case 14:
    __SIMD_fastunpack14_16(in, out, sum);
    break;

  case 15:
    __SIMD_fastunpack15_16(in, out, sum);
    break;

  case 16:
    __SIMD_fastunpack16_16(in, out, sum);
    break;

  default:
    break;
  }
}
__m128i *simdpack_shortlength_u16(const uint16_t *in, int length, __m128i *out,
                                   const uint32_t bit) {
  int k;
  int inwordpointer;
  __m128i P;
  uint32_t firstpass;
  if (bit == 0)
    return out;
  if (bit == 16) {
    memcpy(out, in, length * sizeof(uint16_t));
    return (__m128i *)((uint16_t *)out + length);
  }
  inwordpointer = 0;
  P = _mm_setzero_si128();
  for (k = 0; k < length / 8; ++k) {
    __m128i value = _mm_loadu_si128(((const __m128i *)in + k));
    P = _mm_or_si128(P, _mm_slli_epi16(value, inwordpointer));
    firstpass = 16 - inwordpointer;
    if (bit < firstpass) {
      inwordpointer += bit;
    } else {
      _mm_storeu_si128(out++, P);
      P = _mm_srli_epi16(value, firstpass);
      inwordpointer = bit - firstpass;
    }
  }
  if (length % 8 != 0) {
    uint16_t buffer[8];
    __m128i value;
    for (k = 0; k < (length % 8); ++k) {
      buffer[k] = in[length / 8 * 8 + k];
    }
    for (k = (length % 8); k < 8; ++k) {
      buffer[k] = 0;
    }
    value = _mm_loadu_si128((__m128i *)buffer);
    P = _mm_or_si128(P, _mm_slli_epi16(value, inwordpointer));
    firstpass = 16 - inwordpointer;
    if (bit < firstpass) {
      inwordpointer += bit;
    } else {
      _mm_storeu_si128(out++, P);
      P = _mm_srli_epi16(value, firstpass);
      inwordpointer = bit - firstpass;
    }
  }
  if (inwordpointer != 0) {
    _mm_storeu_si128(out++, P);
  }
  return out;
}

const __m128i *simdunpack_shortlength_u16(const __m128i *in, int length,
                                           uint16_t *out, const uint32_t bit) {
  int k;
  __m128i maskbits;
  int inwordpointer;
  __m128i P;
  if (length == 0)
    return in;
  if (bit == 0) {
    for (k = 0; k < length; ++k) {
      out[k] = 0;
    }
    return in;
  }
  if (bit == 16) {
    memcpy(out, in, length * sizeof(uint16_t));
    return (const __m128i *)((uint16_t *)in + length);
  }
  maskbits = _mm_set1_epi16((1U << bit) - 1);
  inwordpointer = 0;
  P = _mm_loadu_si128((__m128i *)in);
  ++in;
  if (length % 8 == 0) {
    for (k = 0; k + 1 < length / 8; ++k) {
      __m128i answer = _mm_srli_epi16(P, inwordpointer);
      const uint32_t firstpass = 16 - inwordpointer;
      if (bit < firstpass) {
        inwordpointer += bit;
      } else {
        P = _mm_loadu_si128((__m128i *)in);
        ++in;
        answer = _mm_or_si128(_mm_slli_epi16(P, firstpass), answer);
        inwordpointer = bit - firstpass;
      }
      answer = _mm_and_si128(maskbits, answer);
      _mm_storeu_si128((__m128i *)out, answer);
      out += 8;
    }
    if (k < length / 8) {
      __m128i answer = _mm_srli_epi16(P, inwordpointer);
      const uint32_t firstpass = 16 - inwordpointer;
      if (bit < firstpass) {
        inwordpointer += bit;
      } else if (bit == firstpass) {
        inwordpointer = 0;
      } else {
        P = _mm_loadu_si128((__m128i *)in);
        ++in;
        answer = _mm_or_si128(_mm_slli_epi16(P, firstpass), answer);
        inwordpointer = bit - firstpass;
      }
      answer = _mm_and_si128(maskbits, answer);
      _mm_storeu_si128((__m128i *)out, answer);
      out += 8;
    }
  } else {
    for (k = 0; k < length / 8; ++k) {
      __m128i answer = _mm_srli_epi16(P, inwordpointer);
      const uint32_t firstpass = 16 - inwordpointer;
      if (bit < firstpass) {
        inwordpointer += bit;
      } else {
        P = _mm_loadu_si128((__m128i *)in);
        ++in;
        answer = _mm_or_si128(_mm_slli_epi16(P, firstpass), answer);
        inwordpointer = bit - firstpass;
      }
      answer = _mm_and_si128(maskbits, answer);
      _mm_storeu_si128((__m128i *)out, answer);
      out += 8;
    }
    uint16_t buffer[8];
    __m128i answer = _mm_srli_epi16(P, inwordpointer);
    const uint32_t firstpass = 16 - inwordpointer;
    if (bit < firstpass) {
      inwordpointer += bit;
    } else if (bit == firstpass) {
      inwordpointer = 0;
    } else {
      P = _mm_loadu_si128((__m128i *)in);
      ++in;
      answer = _mm_or_si128(_mm_slli_epi16(P, firstpass), answer);
      inwordpointer = bit - firstpass;
    }
    answer = _mm_and_si128(maskbits, answer);
    _mm_storeu_si128((__m128i *)buffer, answer);
    for (k = 0; k < (length % 8); ++k) {
      *out = buffer[k];
      ++out;
    }
  }
  return in;
}

/* returns the integer logarithm of v (bit width) for uint16 */
static uint32_t bits_u16(const uint16_t v) {
  return v == 0 ? 0 : 32 - __builtin_clz((uint32_t)v);
}

static uint32_t oras_u16(const __m128i accumulator) {
  /* Horizontal OR of 8 uint16 lanes into a single uint16 value */
  const __m128i _tmp1 = _mm_or_si128(
      _mm_srli_si128(accumulator, 8), accumulator);
  const __m128i _tmp2 = _mm_or_si128(
      _mm_srli_si128(_tmp1, 4), _tmp1);
  const __m128i _tmp3 = _mm_or_si128(
      _mm_srli_si128(_tmp2, 2), _tmp2);
  return (uint16_t)_mm_extract_epi16(_tmp3, 0);
}

uint32_t maxbits_length_u16(const uint16_t *in, size_t length) {
  size_t k;
  size_t lengthdividedby8 = length / 8;
  size_t offset = lengthdividedby8 * 8;
  uint32_t bigxor = 0;
  if (lengthdividedby8 > 0) {
    const __m128i *pin = (const __m128i *)(in);
    __m128i accumulator = _mm_loadu_si128(pin);
    k = 1;
    for (; 8 * k < 8 * lengthdividedby8; ++k) {
      __m128i newvec = _mm_loadu_si128(pin + k);
      accumulator = _mm_or_si128(accumulator, newvec);
    }
    bigxor = oras_u16(accumulator);
  }
  for (k = offset; k < length; ++k)
    bigxor |= in[k];
  return bits_u16((uint16_t)bigxor);
}

int simdpack_compressedbytes_u16(int length, const uint32_t bit) {
  if (bit == 0)
    return 0;
  if (bit == 16) {
    return length * sizeof(uint16_t);
  }
  /* Each group of 8 uint16 lanes packs to (8 * bit) bits = bit bytes per group.
     Total groups = (length + 7) / 8.  Round up to __m128i boundary. */
  return (((length + 7) / 8) * bit + 15) / 16 * sizeof(__m128i);
}

__m128i *simdpack_length_u16(const uint16_t *in, size_t length, __m128i *out,
                              const uint32_t bit) {
  size_t k;
  for (k = 0; k < length / SIMDBlockSize_u16; ++k) {
    simdpack_u16(in, out, bit);
    in += SIMDBlockSize_u16;
    out += bit;
  }
  return simdpack_shortlength_u16(in, length % SIMDBlockSize_u16, out, bit);
}

const __m128i *simdunpack_length_u16(const __m128i *in, size_t length,
                                      uint16_t *out, const uint32_t bit,
                                      uint32_t *outsum) {
  __m128i sum = _mm_setzero_si128();
  size_t k;
  for (k = 0; k < length / SIMDBlockSize_u16; ++k) {
    simdunpack_u16(in, out, bit, &sum);
    out += SIMDBlockSize_u16;
    in += bit;
  }
  /* Horizontal reduction: 4 x int32 -> 1 x int32 */
  __m128i s = sum;
  s = _mm_add_epi32(s, _mm_shuffle_epi32(s, _MM_SHUFFLE(1,0,3,2)));
  s = _mm_add_epi32(s, _mm_shuffle_epi32(s, _MM_SHUFFLE(2,3,0,1)));

  uint32_t finalsum = (uint32_t)_mm_cvtsi128_si32(s);

  /* Handle remainder with scalar sum */
  size_t remainder = length % SIMDBlockSize_u16;
  if (remainder > 0) {
    in = simdunpack_shortlength_u16(in, remainder, out, bit);
    size_t i;
    for (i = 0; i < remainder; ++i) {
      finalsum += out[i];
    }
  }
  *outsum = finalsum;
  return in;
}


